"""Regenerate notebooks/01_self_improving_copilot_complete.ipynb.

Run: .venv/bin/python tools/make_01_notebook.py
Later plan tasks append sections; keep SECTIONS ordered.
"""

import nbformat as nbf


def md(src):
    return nbf.v4.new_markdown_cell(src)


def code(src):
    return nbf.v4.new_code_cell(src)


# --------------------------------------------------------------------------
# Section: intro
# --------------------------------------------------------------------------
INTRO = [
    md(
        "# 01 - The Self-Improving Copilot\n\n"
        "The CityOps copilot you built in the prerequisite lab could *advise*. "
        "In this notebook it learns to *act* - and to get better at acting:\n\n"
        "1. **Tool registry** - its capabilities become rows it retrieves by meaning\n"
        "2. **Agent loop** - the model calls tools; every call is captured as a full trajectory\n"
        "3. **Verified success** - an LLM judge audits each run against the database record; "
        "only verified runs count (no more `success = bool(final)`) \n"
        "4. **Workflow dedup** - recurring intents merge via an embedding gray band + LLM confirmation\n"
        "5. **Skill harvest & lifecycle** - what recurs *and verifiably works* is distilled into a "
        "`SKILL.md`, born **provisional**, and earns **approved** (or **retired**) through linked outcomes\n\n"
        "Each mechanism closes a gap documented in `memory_promotion_review.md`: promotion without "
        "curation, success without verification, growth without forgetting."
    ),
]

# --------------------------------------------------------------------------
# Section: setup (settings, DB, embedder, chat model, tracing, state gate)
# --------------------------------------------------------------------------
SETUP = [
    md("## 0 · Setup\n\nConnect, verify notebook 00's artifacts, and stand up the in-database embedder."),
    code(
        "import array\n"
        "import json\n"
        "import uuid\n"
        "\n"
        "from cityops_harness.checks import ok, check\n"
        "from cityops_harness.config import load_settings\n"
        "from cityops_harness.db import get_connection\n"
        "from cityops_harness.llm import chat_model\n"
        "from cityops_harness.state import require, verify\n"
        "from cityops_harness.tracing import init_tracing\n"
        "from cityops_harness import improve\n"
        "\n"
        "settings = load_settings()\n"
        "conn = get_connection(settings)\n"
        "require(conn, \"00_setup\")\n"
        "CHAT = chat_model(settings)\n"
        "HANDLER = init_tracing(settings)\n"
        "ok(f\"connected - provider={settings.llm_provider}, langfuse={settings.langfuse_mode}\")"
    ),
    code(
        "# The same IEmbedder bridge the CityOps lab uses: embeddings are computed\n"
        "# inside the database via VECTOR_EMBEDDING() - no text egress, no API cost.\n"
        "import asyncio\n"
        "import numpy as np\n"
        "from langchain_oracledb.embeddings.oracleai import OracleEmbeddings\n"
        "from oracleagentmemory.apis.embedders.embedder import IEmbedder\n"
        "\n"
        "\n"
        "class OracleONNXEmbedder(IEmbedder):\n"
        "    def __init__(self, conn, model_name):\n"
        "        self.provider = OracleEmbeddings(\n"
        "            conn=conn, params={\"provider\": \"database\", \"model\": model_name}\n"
        "        )\n"
        "\n"
        "    def embed(self, texts, *, is_query=False):\n"
        "        return np.asarray(self.provider.embed_documents(list(texts)), dtype=np.float32)\n"
        "\n"
        "    async def embed_async(self, texts, *, is_query=False):\n"
        "        return await asyncio.to_thread(self.embed, texts, is_query=is_query)\n"
        "\n"
        "\n"
        "embedder = OracleONNXEmbedder(conn, settings.embed_model)\n"
        "check(embedder.embed([\"hello\"]).shape == (1, 384), \"in-database embedder returns 384-dim vectors\")"
    ),
]

# --------------------------------------------------------------------------
# Section: domain bootstrap (idempotent - CITY_ASSET, CITY_INSPECTION_FINDING)
# --------------------------------------------------------------------------
BOOTSTRAP = [
    md(
        "## 1 · Domain bootstrap (pre-built)\n\n"
        "The system of record from the CityOps lab, loaded idempotently: the asset registry and\n"
        "~inspection findings with in-database embeddings. Re-running this section is safe."
    ),
    code(
        "from pathlib import Path\n"
        "\n"
        "_data_dir = Path(\"data\") if Path(\"data\").exists() else Path(\"../data\")\n"
        "with open(_data_dir / \"maintenance_logs.json\") as f:\n"
        "    _logs = json.load(f)\n"
        "with open(_data_dir / \"inspection_reports.json\") as f:\n"
        "    _reports = json.load(f)\n"
        "_asset_names = sorted({x[\"asset_name\"] for x in _logs} | {x[\"asset_name\"] for x in _reports})\n"
        "\n"
        "\n"
        "def classify_asset(name: str) -> str:\n"
        "    n = name.lower()\n"
        "    for key, cls in ((\"bridge\", \"bridge\"), (\"tower\", \"tower\"), (\"pump\", \"pump_station\"),\n"
        "                     (\"tunnel\", \"tunnel\"), (\"plant\", \"plant\"), (\"station\", \"station\")):\n"
        "        if key in n:\n"
        "            return cls\n"
        "    return \"structure\"\n"
        "\n"
        "\n"
        "def _table_exists(name: str) -> bool:\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"SELECT COUNT(*) FROM user_tables WHERE table_name = :t\", t=name)\n"
        "        return cur.fetchone()[0] > 0\n"
        "\n"
        "\n"
        "if not _table_exists(\"CITY_ASSET\"):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"CREATE TABLE CITY_ASSET (\n"
        "            asset_id     VARCHAR2(128) PRIMARY KEY,\n"
        "            asset_class  VARCHAR2(32) NOT NULL,\n"
        "            created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\")\n"
        "        cur.executemany(\"INSERT INTO CITY_ASSET (asset_id, asset_class) VALUES (:1, :2)\",\n"
        "                        [(a, classify_asset(a)) for a in _asset_names])\n"
        "    conn.commit()\n"
        "\n"
        "\n"
        "def get_asset(asset_id: str):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"SELECT asset_id, asset_class FROM CITY_ASSET WHERE asset_id = :id\", id=asset_id)\n"
        "        row = cur.fetchone()\n"
        "    return {\"asset_id\": row[0], \"asset_class\": row[1]} if row else None\n"
        "\n"
        "ok(f\"{len(_asset_names)} assets registered\")"
    ),
    code(
        "import os\n"
        "\n"
        "DEMO_FINDING_COUNT = int(os.getenv(\"DEMO_FINDING_COUNT\", \"60\"))\n"
        "\n"
        "if not _table_exists(\"CITY_INSPECTION_FINDING\"):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"CREATE TABLE CITY_INSPECTION_FINDING (\n"
        "            finding_id      VARCHAR2(64) PRIMARY KEY,\n"
        "            asset_id        VARCHAR2(128) NOT NULL,\n"
        "            inspector       VARCHAR2(128),\n"
        "            overall_grade   VARCHAR2(2),\n"
        "            category        VARCHAR2(32),\n"
        "            severity        VARCHAR2(16),\n"
        "            description     CLOB NOT NULL,\n"
        "            recommendation  CLOB,\n"
        "            days_ago        NUMBER,\n"
        "            embedding       VECTOR(384) NOT NULL,\n"
        "            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        "            CONSTRAINT fk_finding_asset FOREIGN KEY (asset_id) REFERENCES CITY_ASSET(asset_id))\"\"\")\n"
        "        try:\n"
        "            cur.execute(\"\"\"CREATE VECTOR INDEX city_finding_embedding_idx\n"
        "                ON CITY_INSPECTION_FINDING (embedding)\n"
        "                ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE\n"
        "                WITH TARGET ACCURACY 95 PARAMETERS (TYPE HNSW, M 16, EFCONSTRUCTION 200)\"\"\")\n"
        "        except Exception as e:\n"
        "            print(f\"  (skipped HNSW index: {e})\")\n"
        "    conn.commit()\n"
        "\n"
        "with conn.cursor() as cur:\n"
        "    cur.execute(\"SELECT COUNT(*) FROM CITY_INSPECTION_FINDING\")\n"
        "    _existing = cur.fetchone()[0]\n"
        "\n"
        "if _existing == 0:\n"
        "    rows = []\n"
        "    for report in _reports:\n"
        "        if len(rows) >= DEMO_FINDING_COUNT:\n"
        "            break\n"
        "        for finding in report[\"findings\"]:\n"
        "            if len(rows) >= DEMO_FINDING_COUNT:\n"
        "                break\n"
        "            vec = array.array('f', embedder.embed([finding[\"description\"]])[0].tolist())\n"
        "            rows.append({\n"
        "                \"finding_id\": str(uuid.uuid4())[:12], \"asset_id\": report[\"asset_name\"],\n"
        "                \"inspector\": report[\"inspector\"], \"overall_grade\": report[\"overall_grade\"],\n"
        "                \"category\": finding[\"category\"], \"severity\": finding[\"severity\"],\n"
        "                \"description\": finding[\"description\"], \"recommendation\": finding[\"recommendation\"],\n"
        "                \"days_ago\": report[\"days_ago\"], \"embedding\": vec,\n"
        "            })\n"
        "    with conn.cursor() as cur:\n"
        "        cur.executemany(\"\"\"INSERT INTO CITY_INSPECTION_FINDING\n"
        "            (finding_id, asset_id, inspector, overall_grade, category, severity,\n"
        "             description, recommendation, days_ago, embedding)\n"
        "            VALUES (:finding_id, :asset_id, :inspector, :overall_grade, :category, :severity,\n"
        "                    :description, :recommendation, :days_ago, :embedding)\"\"\", rows)\n"
        "    conn.commit()\n"
        "    _existing = len(rows)\n"
        "ok(f\"{_existing} findings in the system of record\")"
    ),
    code(
        "def log_finding(asset_id, inspector, category, severity, description,\n"
        "                recommendation=\"\", overall_grade=None, days_ago=0):\n"
        "    finding_id = str(uuid.uuid4())[:12]\n"
        "    vec = array.array('f', embedder.embed([description])[0].tolist())\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"INSERT INTO CITY_INSPECTION_FINDING\n"
        "             (finding_id, asset_id, inspector, overall_grade, category, severity,\n"
        "              description, recommendation, days_ago, embedding)\n"
        "           VALUES (:finding_id, :asset_id, :inspector, :overall_grade, :category, :severity,\n"
        "                   :description, :recommendation, :days_ago, :embedding)\"\"\",\n"
        "            finding_id=finding_id, asset_id=asset_id, inspector=inspector,\n"
        "            overall_grade=overall_grade, category=category, severity=severity,\n"
        "            description=description, recommendation=recommendation,\n"
        "            days_ago=days_ago, embedding=vec)\n"
        "    conn.commit()\n"
        "    return finding_id\n"
        "\n"
        "\n"
        "def find_similar_findings(description, asset_id=None, category=None, k=3):\n"
        "    query_vec = array.array('f', embedder.embed([description])[0].tolist())\n"
        "    sql = \"\"\"SELECT finding_id, asset_id, inspector, overall_grade, category, severity,\n"
        "                    description, recommendation, days_ago,\n"
        "                    VECTOR_DISTANCE(embedding, :q, COSINE) AS score\n"
        "               FROM CITY_INSPECTION_FINDING\n"
        "              WHERE (:asset_id IS NULL OR asset_id = :asset_id)\n"
        "                AND (:category IS NULL OR category = :category)\n"
        "              ORDER BY score FETCH FIRST :k ROWS ONLY\"\"\"\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(sql, q=query_vec, asset_id=asset_id, category=category, k=k)\n"
        "        cols = [d[0].lower() for d in cur.description]\n"
        "        out = []\n"
        "        for r in cur.fetchall():\n"
        "            row = dict(zip(cols, r))\n"
        "            for key in (\"description\", \"recommendation\"):\n"
        "                v = row.get(key)\n"
        "                if v is not None and hasattr(v, \"read\"):\n"
        "                    row[key] = v.read()\n"
        "            out.append(row)\n"
        "    return out\n"
        "\n"
        "ASSET_A = \"Harbor Bridge\" if \"Harbor Bridge\" in _asset_names else _asset_names[0]\n"
        "ASSET_B = next(a for a in _asset_names if a != ASSET_A)\n"
        "ok(f\"domain tools ready - demo assets: {ASSET_A!r}, {ASSET_B!r}\")"
    ),
]

# --------------------------------------------------------------------------
# Section: registry DDL (idempotent)
# --------------------------------------------------------------------------
REGISTRY_DDL = [
    md(
        "## 2 · The harness registries\n\n"
        "Three plain tables the harness *writes to as it learns*:\n\n"
        "- `HARNESS_TOOLS` - capabilities, retrieved by meaning\n"
        "- `HARNESS_WORKFLOW` - captured trajectories with **verified** outcome counts\n"
        "- `HARNESS_SKILLS` - distilled `SKILL.md` documents with a **lifecycle** "
        "(provisional → approved | retired), linked back to outcomes via `skill_id`"
    ),
    code(
        "for ddl in [\n"
        "    \"\"\"CREATE TABLE HARNESS_TOOLS (\n"
        "        name           VARCHAR2(64) PRIMARY KEY,\n"
        "        description    VARCHAR2(1000) NOT NULL,\n"
        "        params_schema  CLOB,\n"
        "        embedding      VECTOR(384) NOT NULL,\n"
        "        created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\",\n"
        "    \"\"\"CREATE TABLE HARNESS_WORKFLOW (\n"
        "        workflow_id        VARCHAR2(64) PRIMARY KEY,\n"
        "        intent             VARCHAR2(2000) NOT NULL,\n"
        "        intent_embedding   VECTOR(384) NOT NULL,\n"
        "        steps              CLOB NOT NULL,\n"
        "        tools_used         VARCHAR2(1000),\n"
        "        occurrences        NUMBER DEFAULT 1,\n"
        "        verified_successes NUMBER DEFAULT 0,\n"
        "        failures           NUMBER DEFAULT 0,\n"
        "        promoted           VARCHAR2(1) DEFAULT 'N',\n"
        "        last_seen          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        "        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\",\n"
        "    \"\"\"CREATE TABLE HARNESS_SKILLS (\n"
        "        skill_id           VARCHAR2(64) PRIMARY KEY,\n"
        "        name               VARCHAR2(128) NOT NULL,\n"
        "        description        VARCHAR2(1000) NOT NULL,\n"
        "        content            CLOB NOT NULL,\n"
        "        sha                VARCHAR2(64) NOT NULL,\n"
        "        status             VARCHAR2(16) DEFAULT 'provisional'\n"
        "                           CHECK (status IN ('provisional','approved','retired')),\n"
        "        schema_sha         VARCHAR2(64),\n"
        "        source_workflow_id VARCHAR2(64),\n"
        "        embedding          VECTOR(384) NOT NULL,\n"
        "        uses               NUMBER DEFAULT 0,\n"
        "        verified_successes NUMBER DEFAULT 0,\n"
        "        failures           NUMBER DEFAULT 0,\n"
        "        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        "        updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\",\n"
        "]:\n"
        "    table = ddl.split(\"CREATE TABLE \")[1].split(\" \")[0].strip()\n"
        "    if not _table_exists(table):\n"
        "        with conn.cursor() as cur:\n"
        "            cur.execute(ddl)\n"
        "        conn.commit()\n"
        "ok(\"HARNESS_TOOLS / HARNESS_WORKFLOW / HARNESS_SKILLS ready\")"
    ),
    code(
        "def current_schema_sha():\n"
        "    \"\"\"Fingerprint of the domain schema a skill was distilled against.\n"
        "    Skills whose stored schema_sha no longer matches are flagged stale at retrieval.\"\"\"\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT table_name, column_name, data_type\n"
        "                         FROM user_tab_columns\n"
        "                        WHERE table_name LIKE 'CITY!_%' ESCAPE '!'\n"
        "                           OR table_name LIKE 'HARNESS!_%' ESCAPE '!'\"\"\")\n"
        "        cols = cur.fetchall()\n"
        "    return improve.compute_schema_sha(cols)\n"
        "\n"
        "SCHEMA_SHA = current_schema_sha()\n"
        "ok(f\"schema fingerprint {SCHEMA_SHA[:12]}...\")"
    ),
]

# --------------------------------------------------------------------------
# Section: toolbox (register + retrieve by meaning)
# --------------------------------------------------------------------------
TOOLBOX_SEC = [
    md(
        "## 3 · The toolbox: capabilities retrieved by meaning\n\n"
        "Each LangChain tool is registered with an embedded description. At run time the\n"
        "agent loop retrieves only the tools relevant to the task - **with a distance\n"
        "threshold**, so an off-topic task injects nothing (one of the review's fixes)."
    ),
    code(
        "from langchain_core.tools import tool\n"
        "\n"
        "CURRENT_INSPECTOR = \"R_Mercer\"\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_find_similar_findings(description: str, asset_id: str = None, k: int = 3) -> str:\n"
        "    \"\"\"Search past inspection findings semantically similar to a description.\n"
        "    Returns finding_id, inspector, severity, recommendation and distance per hit.\"\"\"\n"
        "    hits = find_similar_findings(description, asset_id=asset_id, k=k)\n"
        "    return json.dumps([\n"
        "        {k2: v for k2, v in h.items() if k2 != 'embedding'} for h in hits\n"
        "    ], default=str)\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_log_finding(asset_id: str, category: str, severity: str,\n"
        "                     description: str, recommendation: str = \"\") -> str:\n"
        "    \"\"\"Record a new inspection finding in the system of record.\n"
        "    Returns the new finding_id. Use only after checking similar past findings.\"\"\"\n"
        "    return log_finding(asset_id=asset_id, inspector=CURRENT_INSPECTOR, category=category,\n"
        "                       severity=severity, description=description, recommendation=recommendation)\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_get_asset(asset_id: str) -> str:\n"
        "    \"\"\"Look up an asset's registry record (asset_id, asset_class).\"\"\"\n"
        "    return json.dumps(get_asset(asset_id))\n"
        "\n"
        "\n"
        "TOOLBOX = {t.name: t for t in [tool_find_similar_findings, tool_log_finding, tool_get_asset]}\n"
        "ok(f\"{len(TOOLBOX)} tools defined\")"
    ),
    code(
        "def register_tool(t):\n"
        "    text = f\"{t.name}: {t.description}\"\n"
        "    vec = array.array('f', embedder.embed([text])[0].tolist())\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"DELETE FROM HARNESS_TOOLS WHERE name = :n\", n=t.name)\n"
        "        cur.execute(\"\"\"INSERT INTO HARNESS_TOOLS (name, description, params_schema, embedding)\n"
        "                       VALUES (:n, :d, :p, :e)\"\"\",\n"
        "                    n=t.name, d=t.description, p=json.dumps(t.args), e=vec)\n"
        "    conn.commit()\n"
        "\n"
        "\n"
        "for _t in TOOLBOX.values():\n"
        "    register_tool(_t)\n"
        "\n"
        "TOOL_DISTANCE_MAX = 0.75\n"
        "\n"
        "\n"
        "def retrieve_tools(query: str, k: int = 4):\n"
        "    qv = array.array('f', embedder.embed([query])[0].tolist())\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT name, description, VECTOR_DISTANCE(embedding, :q, COSINE) AS distance\n"
        "                         FROM HARNESS_TOOLS ORDER BY distance FETCH FIRST :k ROWS ONLY\"\"\",\n"
        "                    q=qv, k=k)\n"
        "        rows = [dict(zip([d[0].lower() for d in cur.description], r)) for r in cur.fetchall()]\n"
        "    # ✏️ TODO(1): apply the distance threshold so irrelevant tools are never injected.\n"
        "    #             Use improve.filter_by_distance(rows, TOOL_DISTANCE_MAX).\n"
        "    # TODO-SOLUTION-START\n"
        "    rows = improve.filter_by_distance(rows, TOOL_DISTANCE_MAX)\n"
        "    # TODO-SOLUTION-END\n"
        "    return rows\n"
        "\n"
        "\n"
        "_hits = retrieve_tools(\"corrosion on bridge bearings - check history and record it\")\n"
        "check(len(_hits) >= 2, f\"task-relevant retrieval: {[h['name'] for h in _hits]}\")\n"
        "check(retrieve_tools(\"what is the weather tomorrow in Paris?\") == [],\n"
        "      \"off-topic query injects no tools\")"
    ),
]

# --------------------------------------------------------------------------
# Section: agent loop with full-trajectory capture
# --------------------------------------------------------------------------
AGENT_LOOP = [
    md(
        "## 4 · The agent loop: act, and remember *exactly* what you did\n\n"
        "The review's sharpest finding: the original harness captured a **sorted set of tool\n"
        "names** - nothing to distill from. Here every step records the tool, its **arguments**,\n"
        "and a **truncated result**, in order. That trajectory is what the judge audits and\n"
        "what skills are distilled from."
    ),
    code(
        "from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage\n"
        "\n"
        "AGENT_SYSTEM_PROMPT = (\n"
        "    \"You are the CityOps inspection copilot. You act through tools.\\n\"\n"
        "    \"Rules: check similar past findings BEFORE recording a new one; base severity on\\n\"\n"
        "    \"evidence; when you record a finding, cite its finding_id in your answer.\\n\"\n"
        "    \"Finish with a concise summary (<= 6 sentences).\"\n"
        ")\n"
        "\n"
        "\n"
        "def run_copilot_task(task: str, inspector: str = \"R_Mercer\", use_skills: bool = True,\n"
        "                     max_iters: int = 6) -> dict:\n"
        "    global CURRENT_INSPECTOR\n"
        "    CURRENT_INSPECTOR = inspector\n"
        "    manifest, skill_ids = (build_skill_manifest(task) if use_skills else (\"\", []))\n"
        "    tools_meta = retrieve_tools(task)\n"
        "    lc_tools = [TOOLBOX[t[\"name\"]] for t in tools_meta if t[\"name\"] in TOOLBOX]\n"
        "    model = CHAT.bind_tools(lc_tools) if lc_tools else CHAT\n"
        "    cfg = {\"callbacks\": [HANDLER]} if HANDLER else {}\n"
        "    msgs = [SystemMessage(content=AGENT_SYSTEM_PROMPT + manifest), HumanMessage(content=task)]\n"
        "    trajectory = []\n"
        "    resp = None\n"
        "    for _ in range(max_iters):\n"
        "        resp = model.invoke(msgs, config=cfg)\n"
        "        msgs.append(resp)\n"
        "        if not getattr(resp, \"tool_calls\", None):\n"
        "            break\n"
        "        for tc in resp.tool_calls:\n"
        "            result = str(TOOLBOX[tc[\"name\"]].invoke(tc[\"args\"]))\n"
        "            # ✏️ TODO(2): capture this step for the trajectory - append a dict with\n"
        "            #             the tool name, its args, and improve.truncate_result(result).\n"
        "            # TODO-SOLUTION-START\n"
        "            trajectory.append({\"tool\": tc[\"name\"], \"args\": tc[\"args\"],\n"
        "                               \"result\": improve.truncate_result(result)})\n"
        "            # TODO-SOLUTION-END\n"
        "            msgs.append(ToolMessage(content=result, tool_call_id=tc[\"id\"]))\n"
        "    return {\"answer\": resp.content if resp is not None else \"\",\n"
        "            \"trajectory\": trajectory, \"skill_ids\": skill_ids}\n"
        "\n"
        "\n"
        "def build_skill_manifest(query):  # placeholder until Section 6 redefines it\n"
        "    return \"\", []\n"
        "\n"
        "ok(\"agent loop defined\")"
    ),
]

# --------------------------------------------------------------------------
# Section: the judge (verified success)
# --------------------------------------------------------------------------
JUDGE = [
    md(
        "## 5 · Verified success: the judge audits the database, not the prose\n\n"
        "`success = bool(final)` let confident nonsense count as success. Here an LLM judge\n"
        "sees the task, the full trajectory, the final answer, **and the database evidence**\n"
        "(claimed writes are re-queried). Only a verified run feeds the workflow's success count -\n"
        "and every verdict is logged to Langfuse as a score when tracing is on."
    ),
    code(
        "from pydantic import BaseModel\n"
        "\n"
        "\n"
        "class Verdict(BaseModel):\n"
        "    verified: bool\n"
        "    reason: str\n"
        "\n"
        "\n"
        "JUDGE_PROMPT = (\n"
        "    \"You are auditing one run of an inspection copilot.\\n\"\n"
        "    \"Mark verified=true ONLY if: (a) the trajectory shows the copilot actually did what\\n\"\n"
        "    \"the task required, (b) every write it claims is confirmed by the database evidence,\\n\"\n"
        "    \"and (c) the final answer is consistent with the trajectory. Otherwise verified=false.\\n\"\n"
        "    \"Be strict: an answer that merely SOUNDS complete does not pass.\\n\\n\"\n"
        "    \"# Task\\n{task}\\n\\n# Trajectory\\n{trajectory}\\n\\n# Final answer\\n{answer}\\n\\n\"\n"
        "    \"# Database evidence\\n{evidence}\"\n"
        ")\n"
        "\n"
        "\n"
        "def build_evidence(trajectory):\n"
        "    lines = []\n"
        "    for step in trajectory:\n"
        "        if step[\"tool\"] == \"tool_log_finding\":\n"
        "            fid = step[\"result\"].strip()\n"
        "            with conn.cursor() as cur:\n"
        "                cur.execute(\"\"\"SELECT asset_id, category, severity FROM CITY_INSPECTION_FINDING\n"
        "                               WHERE finding_id = :f\"\"\", f=fid)\n"
        "                row = cur.fetchone()\n"
        "            if row:\n"
        "                lines.append(f\"finding {fid} EXISTS: asset={row[0]} category={row[1]} severity={row[2]}\")\n"
        "            else:\n"
        "                lines.append(f\"finding {fid} NOT FOUND in CITY_INSPECTION_FINDING\")\n"
        "    return \"\\n\".join(lines) or \"(no database writes claimed)\"\n"
        "\n"
        "\n"
        "_judge_model = CHAT.with_structured_output(Verdict)\n"
        "\n"
        "\n"
        "def judge_workflow(task: str, run: dict) -> Verdict:\n"
        "    prompt = JUDGE_PROMPT.format(\n"
        "        task=task,\n"
        "        trajectory=improve.trajectory_to_text(run[\"trajectory\"]),\n"
        "        answer=run[\"answer\"],\n"
        "        evidence=build_evidence(run[\"trajectory\"]),\n"
        "    )\n"
        "    cfg = {\"callbacks\": [HANDLER]} if HANDLER else {}\n"
        "    return _judge_model.invoke(prompt, config=cfg)\n"
        "\n"
        "\n"
        "def record_score(name: str, value: float, comment: str = \"\"):\n"
        "    \"\"\"Log a verdict as a Langfuse score; silently no-ops when tracing is off.\"\"\"\n"
        "    if HANDLER is None:\n"
        "        return\n"
        "    try:\n"
        "        from langfuse import get_client\n"
        "        get_client().create_score(name=name, value=value, comment=comment)\n"
        "        get_client().flush()\n"
        "    except Exception as e:\n"
        "        print(f\"(langfuse score skipped: {e})\")\n"
        "\n"
        "ok(\"judge ready\")"
    ),
]

# --------------------------------------------------------------------------
# Section: workflow capture with gray-band dedup
# --------------------------------------------------------------------------
CAPTURE = [
    md(
        "## 6 · Workflow capture: dedup by meaning, with an honest gray band\n\n"
        "A fixed 0.15 cosine cutoff under-merges paraphrases and over-merges neighbours.\n"
        "Here distances split three ways: certain merge, certain new, and a **gray band**\n"
        "where a cheap LLM call answers 'same task?' before counts are polluted."
    ),
    code(
        "class SameTask(BaseModel):\n"
        "    same: bool\n"
        "\n"
        "\n"
        "_same_task_model = CHAT.with_structured_output(SameTask)\n"
        "\n"
        "\n"
        "def _nearest_workflow(intent_vec):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT workflow_id, intent,\n"
        "                              VECTOR_DISTANCE(intent_embedding, :q, COSINE) AS distance\n"
        "                         FROM HARNESS_WORKFLOW ORDER BY distance FETCH FIRST 1 ROWS ONLY\"\"\",\n"
        "                    q=intent_vec)\n"
        "        row = cur.fetchone()\n"
        "    if row is None:\n"
        "        return None\n"
        "    return {\"workflow_id\": row[0],\n"
        "            \"intent\": row[1].read() if hasattr(row[1], \"read\") else row[1],\n"
        "            \"distance\": row[2]}\n"
        "\n"
        "\n"
        "def capture_workflow(intent: str, run: dict, verified: bool) -> str:\n"
        "    intent_vec = array.array('f', embedder.embed([intent])[0].tolist())\n"
        "    nearest = _nearest_workflow(intent_vec)\n"
        "    decision = \"new\"\n"
        "    if nearest is not None:\n"
        "        # ✏️ TODO(3): decide merge/new. Use improve.merge_decision(nearest['distance']);\n"
        "        #             on 'ask', confirm with the LLM: are `intent` and `nearest['intent']`\n"
        "        #             the same recurring task? (_same_task_model.invoke(...).same)\n"
        "        # TODO-SOLUTION-START\n"
        "        decision = improve.merge_decision(nearest[\"distance\"])\n"
        "        if decision == \"ask\":\n"
        "            q = (f\"Task A: {intent}\\nTask B: {nearest['intent']}\\n\"\n"
        "                 \"Are these the same recurring task type (same procedure, possibly \"\n"
        "                 \"different asset)? Answer same=true/false.\")\n"
        "            decision = \"merge\" if _same_task_model.invoke(q).same else \"new\"\n"
        "        # TODO-SOLUTION-END\n"
        "    if decision == \"merge\":\n"
        "        wid = nearest[\"workflow_id\"]\n"
        "        with conn.cursor() as cur:\n"
        "            # ✏️ TODO(4): only a VERIFIED run may increment verified_successes; an\n"
        "            #             unverified run increments failures. Update occurrences,\n"
        "            #             the right counter, steps (latest verified trajectory), last_seen.\n"
        "            # TODO-SOLUTION-START\n"
        "            if verified:\n"
        "                cur.execute(\"\"\"UPDATE HARNESS_WORKFLOW\n"
        "                               SET occurrences = occurrences + 1,\n"
        "                                   verified_successes = verified_successes + 1,\n"
        "                                   steps = :s, last_seen = CURRENT_TIMESTAMP\n"
        "                             WHERE workflow_id = :w\"\"\",\n"
        "                            s=json.dumps(run[\"trajectory\"], default=str), w=wid)\n"
        "            else:\n"
        "                cur.execute(\"\"\"UPDATE HARNESS_WORKFLOW\n"
        "                               SET occurrences = occurrences + 1,\n"
        "                                   failures = failures + 1,\n"
        "                                   last_seen = CURRENT_TIMESTAMP\n"
        "                             WHERE workflow_id = :w\"\"\", w=wid)\n"
        "            # TODO-SOLUTION-END\n"
        "        conn.commit()\n"
        "        return wid\n"
        "    wid = str(uuid.uuid4())[:12]\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"INSERT INTO HARNESS_WORKFLOW\n"
        "                       (workflow_id, intent, intent_embedding, steps, tools_used,\n"
        "                        verified_successes, failures)\n"
        "                       VALUES (:w, :i, :e, :s, :t, :vs, :f)\"\"\",\n"
        "                    w=wid, i=intent, e=intent_vec,\n"
        "                    s=json.dumps(run[\"trajectory\"], default=str),\n"
        "                    t=\",\".join(sorted({s[\"tool\"] for s in run[\"trajectory\"]})),\n"
        "                    vs=1 if verified else 0, f=0 if verified else 1)\n"
        "    conn.commit()\n"
        "    return wid\n"
        "\n"
        "\n"
        "def run_and_learn(task: str, **kwargs) -> dict:\n"
        "    \"\"\"One full cycle: act -> judge -> record verdict -> capture -> update skill outcomes.\"\"\"\n"
        "    run = run_copilot_task(task, **kwargs)\n"
        "    verdict = judge_workflow(task, run)\n"
        "    record_score(\"workflow_verified\", 1.0 if verdict.verified else 0.0, verdict.reason)\n"
        "    wid = capture_workflow(task, run, verdict.verified)\n"
        "    update_skill_outcomes(run[\"skill_ids\"], verdict.verified)\n"
        "    print(f\"verified={verdict.verified} workflow={wid}\\n  judge: {verdict.reason[:140]}\")\n"
        "    return {\"run\": run, \"verdict\": verdict, \"workflow_id\": wid}\n"
        "\n"
        "\n"
        "def update_skill_outcomes(skill_ids, verified):  # redefined in Section 7\n"
        "    pass\n"
        "\n"
        "ok(\"capture pipeline ready\")"
    ),
]

SECTIONS = [INTRO, SETUP, BOOTSTRAP, REGISTRY_DDL, TOOLBOX_SEC, AGENT_LOOP, JUDGE, CAPTURE]


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "name": "harness",
        "display_name": "CityOps Harness",
        "language": "python",
    }
    nb["cells"] = [cell for section in SECTIONS for cell in section]
    return nb


if __name__ == "__main__":
    nbf.write(build(), "notebooks/01_self_improving_copilot_complete.ipynb")
    print("wrote notebooks/01_self_improving_copilot_complete.ipynb")
