"""Regenerate notebooks/01_self_improving_copilot_complete.ipynb.

Run: .venv/bin/python tools/make_01_notebook.py
Later plan tasks append sections; keep SECTIONS ordered.
"""

import nbformat as nbf


def md(src):
    return nbf.v4.new_markdown_cell(src)


def code(src):
    return nbf.v4.new_code_cell(src)


# --------------------------------------------------------------------------
# Section: intro
# --------------------------------------------------------------------------
INTRO = [
    md(
        "# 01 - The Self-Improving Copilot\n\n"
        "The CityOps copilot you built in the prerequisite lab could *advise*. "
        "In this notebook it learns to *act* - and to get better at acting:\n\n"
        "1. **Tool registry** - its capabilities become rows it retrieves by meaning\n"
        "2. **Agent loop** - the model calls tools; every call is captured as a full trajectory\n"
        "3. **Verified success** - an LLM judge audits each run against the database record; "
        "only verified runs count (no more `success = bool(final)`) \n"
        "4. **Workflow dedup** - recurring intents merge via an embedding gray band + LLM confirmation\n"
        "5. **Skill harvest & lifecycle** - what recurs *and verifiably works* is distilled into a "
        "`SKILL.md`, born **provisional**, and earns **approved** (or **retired**) through linked outcomes\n\n"
        "Each mechanism closes a gap documented in `memory_promotion_review.md`: promotion without "
        "curation, success without verification, growth without forgetting."
    ),
]

# --------------------------------------------------------------------------
# Section: setup (settings, DB, embedder, chat model, tracing, state gate)
# --------------------------------------------------------------------------
SETUP = [
    md("## 0 · Setup\n\nConnect, verify notebook 00's artifacts, and stand up the in-database embedder."),
    code(
        "import array\n"
        "import json\n"
        "import uuid\n"
        "\n"
        "from cityops_harness.checks import ok, check\n"
        "from cityops_harness.config import load_settings\n"
        "from cityops_harness.db import get_connection\n"
        "from cityops_harness.llm import chat_model\n"
        "from cityops_harness.state import require, verify\n"
        "from cityops_harness.tracing import init_tracing\n"
        "from cityops_harness import improve\n"
        "\n"
        "settings = load_settings()\n"
        "conn = get_connection(settings)\n"
        "require(conn, \"00_setup\")\n"
        "CHAT = chat_model(settings)\n"
        "HANDLER = init_tracing(settings)\n"
        "ok(f\"connected - provider={settings.llm_provider}, langfuse={settings.langfuse_mode}\")"
    ),
    code(
        "# The same IEmbedder bridge the CityOps lab uses: embeddings are computed\n"
        "# inside the database via VECTOR_EMBEDDING() - no text egress, no API cost.\n"
        "import asyncio\n"
        "import numpy as np\n"
        "from langchain_oracledb.embeddings.oracleai import OracleEmbeddings\n"
        "from oracleagentmemory.apis.embedders.embedder import IEmbedder\n"
        "\n"
        "\n"
        "class OracleONNXEmbedder(IEmbedder):\n"
        "    def __init__(self, conn, model_name):\n"
        "        self.provider = OracleEmbeddings(\n"
        "            conn=conn, params={\"provider\": \"database\", \"model\": model_name}\n"
        "        )\n"
        "\n"
        "    def embed(self, texts, *, is_query=False):\n"
        "        return np.asarray(self.provider.embed_documents(list(texts)), dtype=np.float32)\n"
        "\n"
        "    async def embed_async(self, texts, *, is_query=False):\n"
        "        return await asyncio.to_thread(self.embed, texts, is_query=is_query)\n"
        "\n"
        "\n"
        "embedder = OracleONNXEmbedder(conn, settings.embed_model)\n"
        "check(embedder.embed([\"hello\"]).shape == (1, 384), \"in-database embedder returns 384-dim vectors\")"
    ),
]

# --------------------------------------------------------------------------
# Section: domain bootstrap (idempotent - CITY_ASSET, CITY_INSPECTION_FINDING)
# --------------------------------------------------------------------------
BOOTSTRAP = [
    md(
        "## 1 · Domain bootstrap (pre-built)\n\n"
        "The system of record from the CityOps lab, loaded idempotently: the asset registry and\n"
        "~inspection findings with in-database embeddings. Re-running this section is safe."
    ),
    md(
        "**Load the asset registry.** Reads the two workshop JSON files, derives the asset\n"
        "list, and classifies each asset by keyword.\n\n"
        "- `CITY_ASSET` is created only if absent, so re-running is a no-op.\n"
        "- `get_asset` is the read path that §3 wraps as an agent tool."
    ),
    code(
        "from pathlib import Path\n"
        "\n"
        "_data_dir = Path(\"data\") if Path(\"data\").exists() else Path(\"../data\")\n"
        "with open(_data_dir / \"maintenance_logs.json\") as f:\n"
        "    _logs = json.load(f)\n"
        "with open(_data_dir / \"inspection_reports.json\") as f:\n"
        "    _reports = json.load(f)\n"
        "_asset_names = sorted({x[\"asset_name\"] for x in _logs} | {x[\"asset_name\"] for x in _reports})\n"
        "\n"
        "\n"
        "def classify_asset(name: str) -> str:\n"
        "    n = name.lower()\n"
        "    for key, cls in ((\"bridge\", \"bridge\"), (\"tower\", \"tower\"), (\"pump\", \"pump_station\"),\n"
        "                     (\"tunnel\", \"tunnel\"), (\"plant\", \"plant\"), (\"station\", \"station\")):\n"
        "        if key in n:\n"
        "            return cls\n"
        "    return \"structure\"\n"
        "\n"
        "\n"
        "def _table_exists(name: str) -> bool:\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"SELECT COUNT(*) FROM user_tables WHERE table_name = :t\", t=name)\n"
        "        return cur.fetchone()[0] > 0\n"
        "\n"
        "\n"
        "if not _table_exists(\"CITY_ASSET\"):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"CREATE TABLE CITY_ASSET (\n"
        "            asset_id     VARCHAR2(128) PRIMARY KEY,\n"
        "            asset_class  VARCHAR2(32) NOT NULL,\n"
        "            created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\")\n"
        "        cur.executemany(\"INSERT INTO CITY_ASSET (asset_id, asset_class) VALUES (:1, :2)\",\n"
        "                        [(a, classify_asset(a)) for a in _asset_names])\n"
        "    conn.commit()\n"
        "\n"
        "\n"
        "def get_asset(asset_id: str):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"SELECT asset_id, asset_class FROM CITY_ASSET WHERE asset_id = :id\", id=asset_id)\n"
        "        row = cur.fetchone()\n"
        "    return {\"asset_id\": row[0], \"asset_class\": row[1]} if row else None\n"
        "\n"
        "ok(f\"{len(_asset_names)} assets registered\")"
    ),
    md(
        "**Load the findings corpus, with embeddings.** Creates\n"
        "`CITY_INSPECTION_FINDING`, then embeds and inserts up to `DEMO_FINDING_COUNT`\n"
        "(60) findings drawn from the inspection reports.\n\n"
        "- Embeddings are computed **inside** the database - no text egress, no API cost.\n"
        "- The HNSW index is wrapped in `try/except`: it speeds up search but is not required.\n"
        "- Skipped entirely when rows already exist."
    ),
    code(
        "import os\n"
        "\n"
        "DEMO_FINDING_COUNT = int(os.getenv(\"DEMO_FINDING_COUNT\", \"60\"))\n"
        "\n"
        "if not _table_exists(\"CITY_INSPECTION_FINDING\"):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"CREATE TABLE CITY_INSPECTION_FINDING (\n"
        "            finding_id      VARCHAR2(64) PRIMARY KEY,\n"
        "            asset_id        VARCHAR2(128) NOT NULL,\n"
        "            inspector       VARCHAR2(128),\n"
        "            overall_grade   VARCHAR2(2),\n"
        "            category        VARCHAR2(32),\n"
        "            severity        VARCHAR2(16),\n"
        "            description     CLOB NOT NULL,\n"
        "            recommendation  CLOB,\n"
        "            days_ago        NUMBER,\n"
        "            embedding       VECTOR(384) NOT NULL,\n"
        "            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        "            CONSTRAINT fk_finding_asset FOREIGN KEY (asset_id) REFERENCES CITY_ASSET(asset_id))\"\"\")\n"
        "        try:\n"
        "            cur.execute(\"\"\"CREATE VECTOR INDEX city_finding_embedding_idx\n"
        "                ON CITY_INSPECTION_FINDING (embedding)\n"
        "                ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE\n"
        "                WITH TARGET ACCURACY 95 PARAMETERS (TYPE HNSW, M 16, EFCONSTRUCTION 200)\"\"\")\n"
        "        except Exception as e:\n"
        "            print(f\"  (skipped HNSW index: {e})\")\n"
        "    conn.commit()\n"
        "\n"
        "with conn.cursor() as cur:\n"
        "    cur.execute(\"SELECT COUNT(*) FROM CITY_INSPECTION_FINDING\")\n"
        "    _existing = cur.fetchone()[0]\n"
        "\n"
        "if _existing == 0:\n"
        "    rows = []\n"
        "    for report in _reports:\n"
        "        if len(rows) >= DEMO_FINDING_COUNT:\n"
        "            break\n"
        "        for finding in report[\"findings\"]:\n"
        "            if len(rows) >= DEMO_FINDING_COUNT:\n"
        "                break\n"
        "            vec = array.array('f', embedder.embed([finding[\"description\"]])[0].tolist())\n"
        "            rows.append({\n"
        "                \"finding_id\": str(uuid.uuid4())[:12], \"asset_id\": report[\"asset_name\"],\n"
        "                \"inspector\": report[\"inspector\"], \"overall_grade\": report[\"overall_grade\"],\n"
        "                \"category\": finding[\"category\"], \"severity\": finding[\"severity\"],\n"
        "                \"description\": finding[\"description\"], \"recommendation\": finding[\"recommendation\"],\n"
        "                \"days_ago\": report[\"days_ago\"], \"embedding\": vec,\n"
        "            })\n"
        "    with conn.cursor() as cur:\n"
        "        cur.executemany(\"\"\"INSERT INTO CITY_INSPECTION_FINDING\n"
        "            (finding_id, asset_id, inspector, overall_grade, category, severity,\n"
        "             description, recommendation, days_ago, embedding)\n"
        "            VALUES (:finding_id, :asset_id, :inspector, :overall_grade, :category, :severity,\n"
        "                    :description, :recommendation, :days_ago, :embedding)\"\"\", rows)\n"
        "    conn.commit()\n"
        "    _existing = len(rows)\n"
        "ok(f\"{_existing} findings in the system of record\")"
    ),
    md(
        "**The two domain operations, plus the demo's asset picks.** `log_finding` writes a\n"
        "finding and embeds its description on the way in; `find_similar_findings` does the\n"
        "cosine top-k search, optionally filtered by asset or category.\n\n"
        "- Both are plain Python here - §3 wraps them as agent tools.\n"
        "- `ASSET_B` is deliberately chosen from the same asset *class* as `ASSET_A`, so §8's\n"
        "  corrosion task makes sense against both. An unrelated pick makes the model either\n"
        "  refuse to log a nonsensical finding or invent an `asset_id` that breaks the\n"
        "  foreign key."
    ),
    code(
        "def log_finding(asset_id, inspector, category, severity, description,\n"
        "                recommendation=\"\", overall_grade=None, days_ago=0):\n"
        "    finding_id = str(uuid.uuid4())[:12]\n"
        "    vec = array.array('f', embedder.embed([description])[0].tolist())\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"INSERT INTO CITY_INSPECTION_FINDING\n"
        "             (finding_id, asset_id, inspector, overall_grade, category, severity,\n"
        "              description, recommendation, days_ago, embedding)\n"
        "           VALUES (:finding_id, :asset_id, :inspector, :overall_grade, :category, :severity,\n"
        "                   :description, :recommendation, :days_ago, :embedding)\"\"\",\n"
        "            finding_id=finding_id, asset_id=asset_id, inspector=inspector,\n"
        "            overall_grade=overall_grade, category=category, severity=severity,\n"
        "            description=description, recommendation=recommendation,\n"
        "            days_ago=days_ago, embedding=vec)\n"
        "    conn.commit()\n"
        "    return finding_id\n"
        "\n"
        "\n"
        "def find_similar_findings(description, asset_id=None, category=None, k=3):\n"
        "    query_vec = array.array('f', embedder.embed([description])[0].tolist())\n"
        "    sql = \"\"\"SELECT finding_id, asset_id, inspector, overall_grade, category, severity,\n"
        "                    description, recommendation, days_ago,\n"
        "                    VECTOR_DISTANCE(embedding, :q, COSINE) AS score\n"
        "               FROM CITY_INSPECTION_FINDING\n"
        "              WHERE (:asset_id IS NULL OR asset_id = :asset_id)\n"
        "                AND (:category IS NULL OR category = :category)\n"
        "              ORDER BY score FETCH FIRST :k ROWS ONLY\"\"\"\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(sql, q=query_vec, asset_id=asset_id, category=category, k=k)\n"
        "        cols = [d[0].lower() for d in cur.description]\n"
        "        out = []\n"
        "        for r in cur.fetchall():\n"
        "            row = dict(zip(cols, r))\n"
        "            for key in (\"description\", \"recommendation\"):\n"
        "                v = row.get(key)\n"
        "                if v is not None and hasattr(v, \"read\"):\n"
        "                    row[key] = v.read()\n"
        "            out.append(row)\n"
        "    return out\n"
        "\n"
        "ASSET_A = \"Harbor Bridge\" if \"Harbor Bridge\" in _asset_names else _asset_names[0]\n"
        "# Pick a second asset of the SAME class as ASSET_A (not just alphabetically-next) so\n"
        "# the demo's structural-corrosion task actually makes sense against it - the naive\n"
        "# 'first other name' pick can land on an unrelated asset (e.g. a sensor), and the\n"
        "# model then declines to log a nonsensical finding or invents an asset_id, which\n"
        "# violates the CITY_INSPECTION_FINDING -> CITY_ASSET foreign key.\n"
        "_a_class = classify_asset(ASSET_A)\n"
        "ASSET_B = (\n"
        "    next((a for a in _asset_names if a != ASSET_A and classify_asset(a) == _a_class\n"
        "          and \"Sensor\" not in a), None)\n"
        "    or next((a for a in _asset_names if a != ASSET_A and classify_asset(a) == _a_class), None)\n"
        "    or next(a for a in _asset_names if a != ASSET_A)\n"
        ")\n"
        "ok(f\"domain tools ready - demo assets: {ASSET_A!r}, {ASSET_B!r}\")"
    ),
]

# --------------------------------------------------------------------------
# Section: registry DDL (idempotent)
# --------------------------------------------------------------------------
REGISTRY_DDL = [
    md(
        "## 2 · The harness registries\n\n"
        "Three plain tables the harness *writes to as it learns*:\n\n"
        "- `HARNESS_TOOLS` - capabilities, retrieved by meaning\n"
        "- `HARNESS_WORKFLOW` - captured trajectories with **verified** outcome counts\n"
        "- `HARNESS_SKILLS` - distilled `SKILL.md` documents with a **lifecycle** "
        "(provisional → approved | retired), linked back to outcomes via `skill_id`"
    ),
    md(
        "**Create the three registries the harness writes to as it learns.**\n\n"
        "- `HARNESS_TOOLS` - the tool catalogue, mapping each tool to a capability group\n"
        "  (no embeddings; discovery is by progressive disclosure in Section 3).\n"
        "- `HARNESS_WORKFLOW` - one row per *recurring task type*; `occurrences`,\n"
        "  `verified_successes` and `failures` are what the harvest gate reads.\n"
        "- `HARNESS_SKILLS` - distilled procedures; `status` carries the lifecycle\n"
        "  (provisional → approved → retired).\n"
        "- Every `CREATE TABLE` is guarded by `_table_exists`, so the section is idempotent."
    ),
    code(
        "# HARNESS_TOOLS is a per-run catalogue mapping each tool to a capability group.\n"
        "# It is rebuilt from the tool set every run, so drop+recreate rather than\n"
        "# create-if-absent. No embeddings: tool discovery is by capability disclosure\n"
        "# (Section 3), not similarity search.\n"
        "with conn.cursor() as cur:\n"
        "    try:\n"
        "        cur.execute(\"DROP TABLE HARNESS_TOOLS PURGE\")\n"
        "    except Exception:\n"
        "        pass\n"
        "    cur.execute(\"\"\"CREATE TABLE HARNESS_TOOLS (\n"
        "        name        VARCHAR2(64) PRIMARY KEY,\n"
        "        description VARCHAR2(1000),\n"
        "        group_name  VARCHAR2(32))\"\"\")\n"
        "conn.commit()\n"
        "\n"
        "for ddl in [\n"
        "    \"\"\"CREATE TABLE HARNESS_WORKFLOW (\n"
        "        workflow_id        VARCHAR2(64) PRIMARY KEY,\n"
        "        intent             VARCHAR2(2000) NOT NULL,\n"
        "        intent_embedding   VECTOR(384) NOT NULL,\n"
        "        steps              CLOB NOT NULL,\n"
        "        tools_used         VARCHAR2(1000),\n"
        "        occurrences        NUMBER DEFAULT 1,\n"
        "        verified_successes NUMBER DEFAULT 0,\n"
        "        failures           NUMBER DEFAULT 0,\n"
        "        promoted           VARCHAR2(1) DEFAULT 'N',\n"
        "        last_seen          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        "        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\",\n"
        "    \"\"\"CREATE TABLE HARNESS_SKILLS (\n"
        "        skill_id           VARCHAR2(64) PRIMARY KEY,\n"
        "        name               VARCHAR2(128) NOT NULL,\n"
        "        description        VARCHAR2(1000) NOT NULL,\n"
        "        content            CLOB NOT NULL,\n"
        "        sha                VARCHAR2(64) NOT NULL,\n"
        "        status             VARCHAR2(16) DEFAULT 'provisional'\n"
        "                           CHECK (status IN ('provisional','approved','retired')),\n"
        "        source_workflow_id VARCHAR2(64),\n"
        "        embedding          VECTOR(384) NOT NULL,\n"
        "        uses               NUMBER DEFAULT 0,\n"
        "        verified_successes NUMBER DEFAULT 0,\n"
        "        failures           NUMBER DEFAULT 0,\n"
        "        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        "        updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\",\n"
        "]:\n"
        "    table = ddl.split(\"CREATE TABLE \")[1].split(\" \")[0].strip()\n"
        "    if not _table_exists(table):\n"
        "        with conn.cursor() as cur:\n"
        "            cur.execute(ddl)\n"
        "        conn.commit()\n"
        "\n"
        "# Start each run from a clean LEARNED state. The tables persist across runs, but\n"
        "# their ROWS are this run's learning - leaving them makes a second run inherit stale\n"
        "# workflows/skills (harvest can't re-fire; the anatomy's STEP 2 shows a leftover\n"
        "# skill instead of 'none'). Clearing the rows makes the notebook re-runnable. Only the\n"
        "# learned HARNESS_% tables are touched - never the CITY_% domain data.\n"
        "with conn.cursor() as cur:\n"
        "    for _t in (\"HARNESS_WORKFLOW\", \"HARNESS_SKILLS\"):\n"
        "        cur.execute(f\"DELETE FROM {_t}\")\n"
        "conn.commit()\n"
        "ok(\"HARNESS_TOOLS / HARNESS_WORKFLOW / HARNESS_SKILLS ready - learned state reset\")"
    ),
    md(
        "**An inspector for the registries.** Defined once here and called after every cell\n"
        "that writes, so you can watch rows appear, merge, and change status as you run.\n\n"
        "- Right now everything is empty - this is the baseline to compare against.\n"
        "- Watch three things as the notebook runs: `occurrences` climbing on **one**\n"
        "  workflow row rather than spawning new ones, `promoted` flipping to `Y`, and a\n"
        "  skill's `status` going `provisional → approved`."
    ),
    code(
        "def show_registries(label=\"\", tools=False):\n"
        "    \"\"\"Snapshot the harness registries. Call after any cell that writes to them.\"\"\"\n"
        "    print(f\"===== {label} =====\" if label else \"=====\")\n"
        "    if tools:\n"
        "        with conn.cursor() as cur:\n"
        "            cur.execute(\"SELECT name, group_name FROM HARNESS_TOOLS \"\n"
        "                        \"ORDER BY group_name, name\")\n"
        "            _rows = cur.fetchall()\n"
        "        _cat = ', '.join(f\"{n}[{g}]\" for n, g in _rows) or '(empty)'\n"
        "        print(f\"HARNESS_TOOLS    ({len(_rows)}): {_cat}\")\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT workflow_id, occurrences, verified_successes, failures,\n"
        "                              promoted, intent\n"
        "                         FROM HARNESS_WORKFLOW ORDER BY created_at\"\"\")\n"
        "        wf = cur.fetchall()\n"
        "    print(f\"HARNESS_WORKFLOW ({len(wf)} row(s))\")\n"
        "    for wid, occ, vs, fl, pr, intent in wf:\n"
        "        text = intent.read() if hasattr(intent, \"read\") else (intent or \"\")\n"
        "        print(f\"   {wid}  occurrences={occ} verified={vs} failed={fl} promoted={pr}\")\n"
        "        print(f\"      intent: {text[:70]}\")\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT skill_id, status, uses, verified_successes, failures, name\n"
        "                         FROM HARNESS_SKILLS ORDER BY created_at\"\"\")\n"
        "        sk = cur.fetchall()\n"
        "    print(f\"HARNESS_SKILLS   ({len(sk)} row(s))\")\n"
        "    for sid, status, uses, vs, fl, name in sk:\n"
        "        print(f\"   {sid}  {status:<11} uses={uses} verified={vs} failed={fl}  {name}\")\n"
        "    print()\n"
        "\n"
        "show_registries(\"baseline - registries exist, nothing learned yet\", tools=True)"
    ),
]

# --------------------------------------------------------------------------
# Section: toolbox (register + retrieve by meaning)
# --------------------------------------------------------------------------
TOOLBOX_SEC = [
    md(
        "## 3 · The toolbox: a hot core + progressively-disclosed capabilities\n\n"
        "Similarity search over tool embeddings is finicky - it needs a distance threshold\n"
        "that is easy to mis-calibrate, and a task's wording can silently drop a tool it\n"
        "needed. Instead this notebook uses **progressive disclosure**:\n\n"
        "- a small **hot set** of always-available tools (the search → log core), so the\n"
        "  common task needs no lookup at all; and\n"
        "- the rest grouped by capability behind a **meta-tool**, `open_capability`, that the\n"
        "  agent calls to *disclose* a group's tools when it needs them.\n\n"
        "The agent reads a short **routing rubric** (\"if you need X, open A\") and picks a\n"
        "group, then a tool - no embeddings, no threshold, and context stays bounded no\n"
        "matter how large the catalogue grows."
    ),
    md(
        "**Declare the tools.** Thin `@tool` wrappers over the domain functions - a couple of\n"
        "reads and writes beyond §1's core, so the capability groups have real members.\n\n"
        "- The docstring **is the interface** the model reads to choose and call a tool.\n"
        "- `tool_log_finding` reads the module-level `CURRENT_INSPECTOR`, which §4 sets per run.\n"
        "- `TOOLBOX` maps name → callable; §4 executes whatever the model asks for."
    ),
    code(
        "from langchain_core.tools import tool\n"
        "\n"
        "CURRENT_INSPECTOR = \"R_Mercer\"\n"
        "\n"
        "\n"
        "# --- extra domain reads/writes the new tools wrap (the first three are from Section 1) ---\n"
        "def recent_findings(asset_id, limit=5):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT finding_id, category, severity, days_ago\n"
        "                       FROM CITY_INSPECTION_FINDING WHERE asset_id = :a\n"
        "                       ORDER BY days_ago FETCH FIRST :n ROWS ONLY\"\"\", a=asset_id, n=limit)\n"
        "        return [{\"finding_id\": r[0], \"category\": r[1], \"severity\": r[2], \"days_ago\": r[3]}\n"
        "                for r in cur.fetchall()]\n"
        "\n"
        "\n"
        "def finding_detail(finding_id):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT asset_id, category, severity,\n"
        "                              DBMS_LOB.SUBSTR(description, 600, 1), recommendation, days_ago\n"
        "                       FROM CITY_INSPECTION_FINDING WHERE finding_id = :f\"\"\", f=finding_id)\n"
        "        r = cur.fetchone()\n"
        "    if not r:\n"
        "        return {\"error\": f\"no finding {finding_id}\"}\n"
        "    return {\"finding_id\": finding_id, \"asset_id\": r[0], \"category\": r[1],\n"
        "            \"severity\": r[2], \"description\": r[3], \"recommendation\": r[4], \"days_ago\": r[5]}\n"
        "\n"
        "\n"
        "def amend_finding(finding_id, column, value):\n"
        "    if column not in (\"severity\", \"recommendation\"):\n"
        "        raise ValueError(\"only severity or recommendation may be amended\")\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(f\"UPDATE CITY_INSPECTION_FINDING SET {column} = :v WHERE finding_id = :f\",\n"
        "                    v=value, f=finding_id)\n"
        "        n = cur.rowcount\n"
        "    conn.commit()\n"
        "    return n\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_find_similar_findings(description: str, asset_id: str = None, k: int = 3) -> str:\n"
        "    \"\"\"Search past inspection findings semantically similar to a description.\n"
        "    Returns finding_id, inspector, severity, recommendation and distance per hit.\"\"\"\n"
        "    hits = find_similar_findings(description, asset_id=asset_id, k=k)\n"
        "    return json.dumps([\n"
        "        {k2: v for k2, v in h.items() if k2 != 'embedding'} for h in hits\n"
        "    ], default=str)\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_log_finding(asset_id: str, category: str, severity: str,\n"
        "                     description: str, recommendation: str = \"\") -> str:\n"
        "    \"\"\"Record a new inspection finding in the system of record.\n"
        "    Returns the new finding_id. Use only after checking similar past findings.\"\"\"\n"
        "    return log_finding(asset_id=asset_id, inspector=CURRENT_INSPECTOR, category=category,\n"
        "                       severity=severity, description=description, recommendation=recommendation)\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_get_asset(asset_id: str) -> str:\n"
        "    \"\"\"Look up an asset's registry record (asset_id, asset_class).\"\"\"\n"
        "    return json.dumps(get_asset(asset_id))\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_recent_findings(asset_id: str, limit: int = 5) -> str:\n"
        "    \"\"\"List an asset's most recent findings (finding_id, category, severity, days_ago).\"\"\"\n"
        "    return json.dumps(recent_findings(asset_id, limit), default=str)\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_finding_detail(finding_id: str) -> str:\n"
        "    \"\"\"Get the full detail of one finding by its finding_id.\"\"\"\n"
        "    return json.dumps(finding_detail(finding_id), default=str)\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_update_severity(finding_id: str, severity: str) -> str:\n"
        "    \"\"\"Amend an existing finding's severity (low/medium/high). Returns rows changed.\"\"\"\n"
        "    return f\"updated {amend_finding(finding_id, 'severity', severity)} finding(s)\"\n"
        "\n"
        "\n"
        "@tool\n"
        "def tool_set_recommendation(finding_id: str, recommendation: str) -> str:\n"
        "    \"\"\"Set or replace the recommendation on an existing finding. Returns rows changed.\"\"\"\n"
        "    return f\"updated {amend_finding(finding_id, 'recommendation', recommendation)} finding(s)\"\n"
        "\n"
        "\n"
        "TOOLBOX = {t.name: t for t in [\n"
        "    tool_find_similar_findings, tool_log_finding, tool_get_asset,\n"
        "    tool_recent_findings, tool_finding_detail, tool_update_severity, tool_set_recommendation]}\n"
        "ok(f\"{len(TOOLBOX)} tools defined\")"
    ),
    md(
        "**Hot set, capability groups, and the meta-tool.** `HOT` is always bound. `GROUPS`\n"
        "buckets the rest by high-level function, each with a *when-to-reach-for-it* line;\n"
        "those lines become the `CAPABILITY_RUBRIC` the agent reads. `open_capability(group)`\n"
        "is the unlock - calling it makes that group's tools bindable on the next step.\n\n"
        "- `HARNESS_TOOLS` records each tool under its group (`hot` for the core) - a\n"
        "  catalogue, no embeddings.\n"
        "- The two `check(...)`s assert the shape: hot tools always present, grouped tools\n"
        "  cold until disclosed."
    ),
    code(
        "# HOT set: always bound. The search -> log core covers the common inspection task,\n"
        "# so most tasks never touch the meta-tool.\n"
        "HOT = [\"tool_find_similar_findings\", \"tool_log_finding\"]\n"
        "\n"
        "# COLD tail: grouped by capability, disclosed on demand. Each group carries a\n"
        "# 'when to reach for it' line - the routing rubric the agent reads.\n"
        "GROUPS = {\n"
        "    \"inspection\": {\n"
        "        \"when\": \"look up an asset's class, list its recent findings, or read the full \"\n"
        "                \"detail of a specific finding\",\n"
        "        \"tools\": [\"tool_get_asset\", \"tool_recent_findings\", \"tool_finding_detail\"],\n"
        "    },\n"
        "    \"recording\": {\n"
        "        \"when\": \"amend an EXISTING finding - change its severity or set its recommendation\",\n"
        "        \"tools\": [\"tool_update_severity\", \"tool_set_recommendation\"],\n"
        "    },\n"
        "}\n"
        "\n"
        "# The routing rubric: conditionals, not bare labels, so the agent maps need -> group\n"
        "# without guessing. This goes into the agent's instructions (see Section 4).\n"
        "CAPABILITY_RUBRIC = \"\\n\".join(\n"
        "    f\"  - If you need to {g['when']}, call open_capability('{name}').\"\n"
        "    for name, g in GROUPS.items())\n"
        "\n"
        "\n"
        "@tool\n"
        "def open_capability(group: str) -> str:\n"
        "    \"\"\"Unlock a group of extra tools when the always-available core tools are not\n"
        "    enough. The capability guide in your instructions says which group to open for\n"
        "    what. After you open a group, its tools become callable on your next step.\"\"\"\n"
        "    if group not in GROUPS:\n"
        "        return f\"ERROR: no capability '{group}'. Choose one of: {list(GROUPS)}\"\n"
        "    return f\"opened '{group}'. Now available: {', '.join(GROUPS[group]['tools'])}\"\n"
        "\n"
        "TOOLBOX[\"open_capability\"] = open_capability\n"
        "\n"
        "\n"
        "# The catalogue: record each tool under its group ('hot' for the always-bound core).\n"
        "def register_tool(name, description, group_name):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"DELETE FROM HARNESS_TOOLS WHERE name = :n\", n=name)\n"
        "        cur.execute(\"INSERT INTO HARNESS_TOOLS (name, description, group_name) \"\n"
        "                    \"VALUES (:n, :d, :g)\", n=name, d=str(description)[:1000], g=group_name)\n"
        "    conn.commit()\n"
        "\n"
        "\n"
        "for _n in HOT:\n"
        "    register_tool(_n, TOOLBOX[_n].description, \"hot\")\n"
        "for _grp, _spec in GROUPS.items():\n"
        "    for _n in _spec[\"tools\"]:\n"
        "        register_tool(_n, TOOLBOX[_n].description, _grp)\n"
        "\n"
        "print(\"routing rubric the agent will read:\\n\" + CAPABILITY_RUBRIC)\n"
        "check(all(n in TOOLBOX for n in HOT), \"hot tools are always available\")\n"
        "check(all(n not in HOT for g in GROUPS.values() for n in g[\"tools\"]),\n"
        "      \"grouped tools are cold - reachable only after open_capability\")"
    ),
    md(
        "**Registry check.** `HARNESS_TOOLS` now catalogues all seven tools by group. The\n"
        "other two registries are still empty - tools are *declared*, workflows and skills\n"
        "are *learned*."
    ),
    code("show_registries(\"after tool registration\", tools=True)"),
]

# --------------------------------------------------------------------------
# Section: agent loop with full-trajectory capture
# --------------------------------------------------------------------------
AGENT_LOOP = [
    md(
        "## 4 · The agent loop: act, and remember *exactly* what you did\n\n"
        "The review's sharpest finding: the original harness captured a **sorted set of tool\n"
        "names** - nothing to distill from. Here every step records the tool, its **arguments**,\n"
        "and a **truncated result**, in order. That trajectory is what the judge audits and\n"
        "what skills are distilled from."
    ),
    md(
        "**The act loop, and the trajectory it leaves behind.** Builds the system prompt\n"
        "(plus any skill manifest), binds *only* the retrieved tools, then iterates:\n"
        "model → tool calls → results → model, up to `max_iters`.\n\n"
        "- Each step appends `{tool, args, truncated result}` - the record §5's judge audits\n"
        "  and §7 distils skills from.\n"
        "- A tool error becomes `ERROR: ...` text in the `ToolMessage` rather than a crash, so\n"
        "  the model can recover and the failure stays visible in the trajectory.\n"
        "- The model sees the **full** result; the trajectory stores the first 300 chars.\n"
        "- The final `content` flatten exists because Anthropic returns a list of content\n"
        "  blocks where OpenAI and Ollama return a plain string."
    ),
    code(
        "from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage\n"
        "\n"
        "AGENT_SYSTEM_PROMPT = (\n"
        "    \"You are the CityOps inspection copilot. You act through tools.\\n\"\n"
        "    \"Rules: check similar past findings BEFORE recording a new one; base severity on\\n\"\n"
        "    \"evidence; when you record a finding, cite its finding_id in your answer.\\n\"\n"
        "    \"Your final summary will be audited against the tool call results above - state\\n\"\n"
        "    \"only facts, figures, and comparisons that actually appear in those results; do not\\n\"\n"
        "    \"add estimates, trends, or specifics you did not retrieve.\\n\"\n"
        "    \"Finish with a concise summary (<= 6 sentences).\"\n"
        ")\n"
        "\n"
        "\n"
        "def run_copilot_task(task: str, inspector: str = \"R_Mercer\", use_skills: bool = True,\n"
        "                     max_iters: int = 6) -> dict:\n"
        "    global CURRENT_INSPECTOR\n"
        "    CURRENT_INSPECTOR = inspector\n"
        "    manifest, skill_ids = (build_skill_manifest(task) if use_skills else (\"\", []))\n"
        "    cfg = {\"callbacks\": [HANDLER]} if HANDLER else {}\n"
        "    opened = set()   # capability groups disclosed so far this task\n"
        "\n"
        "    # ✏️ TODO(1): compose the tools bound this turn - the HOT core + open_capability +\n"
        "    #             the tools of every group already in `opened`. This is what re-binds\n"
        "    #             as the agent discloses more capabilities.\n"
        "    def bound_tools():\n"
        "        # TODO-SOLUTION-START\n"
        "        names = list(HOT) + [n for g in opened for n in GROUPS[g][\"tools\"]]\n"
        "        return [TOOLBOX[n] for n in names] + [open_capability]\n"
        "        # TODO-SOLUTION-END\n"
        "\n"
        "    sys = (AGENT_SYSTEM_PROMPT + manifest\n"
        "           + \"\\n\\nYou start with the core tools. To reach others:\\n\" + CAPABILITY_RUBRIC)\n"
        "    msgs = [SystemMessage(content=sys), HumanMessage(content=task)]\n"
        "    trajectory = []\n"
        "    resp = None\n"
        "    for _ in range(max_iters):\n"
        "        # re-bind every turn: newly opened groups become callable here\n"
        "        resp = CHAT.bind_tools(bound_tools()).invoke(msgs, config=cfg)\n"
        "        msgs.append(resp)\n"
        "        if not getattr(resp, \"tool_calls\", None):\n"
        "            break\n"
        "        for tc in resp.tool_calls:\n"
        "            if tc[\"name\"] == \"open_capability\" and tc[\"args\"].get(\"group\") in GROUPS:\n"
        "                opened.add(tc[\"args\"][\"group\"])   # disclose: bindable next turn\n"
        "            try:\n"
        "                # `cfg` carries the Langfuse callback: pass it here too, or the tool\n"
        "                # executions run outside the trace and only the model calls are visible.\n"
        "                result = str(TOOLBOX[tc[\"name\"]].invoke(tc[\"args\"], cfg))\n"
        "            except Exception as e:\n"
        "                # A tool error becomes ToolMessage content, not a crashed run: the\n"
        "                # model sees it and can recover, and the judge sees it in the trajectory.\n"
        "                result = f\"ERROR: {type(e).__name__}: {e}\"\n"
        "            # ✏️ TODO(2): capture this step for the trajectory - append a dict with\n"
        "            #             the tool name, its args, and improve.truncate_result(result).\n"
        "            # TODO-SOLUTION-START\n"
        "            trajectory.append({\"tool\": tc[\"name\"], \"args\": tc[\"args\"],\n"
        "                               \"result\": improve.truncate_result(result)})\n"
        "            # TODO-SOLUTION-END\n"
        "            msgs.append(ToolMessage(content=result, tool_call_id=tc[\"id\"]))\n"
        "    answer = resp.content if resp is not None else \"\"\n"
        "    if isinstance(answer, list):\n"
        "        # Some providers return content as a list of content-block dicts rather than\n"
        "        # a plain string; flatten to text so downstream string ops don't break.\n"
        "        answer = \"\".join(\n"
        "            p.get(\"text\", \"\") if isinstance(p, dict) else str(p) for p in answer\n"
        "        )\n"
        "    return {\"answer\": answer, \"trajectory\": trajectory, \"skill_ids\": skill_ids}\n"
        "\n"
        "\n"
        "def build_skill_manifest(query):  # placeholder until Section 6 redefines it\n"
        "    return \"\", []\n"
        "\n"
        "ok(\"agent loop defined\")"
    ),
]

# --------------------------------------------------------------------------
# Section: the judge (verified success)
# --------------------------------------------------------------------------
JUDGE = [
    md(
        "## 5 · Verified success: the judge audits the database, not the prose\n\n"
        "`success = bool(final)` let confident nonsense count as success. Here an LLM judge\n"
        "sees the task, the full trajectory, the final answer, **and database evidence** -\n"
        "every finding_id the answer names, re-queried against the record. Only a verified run\n"
        "feeds the workflow's success count, and every verdict is logged to Langfuse when on.\n\n"
        "> **This is a pattern, not a `finding_id` trick.** The idea is *verify your agent's\n"
        "> checkable side effect against ground truth.* In this domain that side effect is a\n"
        "> database row with an id; in yours it might be a created ticket, a passing test, a\n"
        "> committed file, or an HTTP 200. Pick the thing you can check, and check it."
    ),
    md(
        "**Audit the run against the database, not the prose.** `build_evidence` re-queries\n"
        "every `finding_id` the answer names - the one it recorded, plus any priors it cites -\n"
        "and marks each `EXISTS` or `NOT FOUND`. It is **plain SQL, run before the judge**, so\n"
        "the ground truth is non-negotiable. The judge then sees task, trajectory, answer, and\n"
        "that evidence.\n\n"
        "- Structured output makes `verified` a real bool, not text to be parsed.\n"
        "- Interpretive judgement (severity reasoning, recommendations) explicitly passes; a\n"
        "  fabricated finding_id or an action absent from the trajectory explicitly fails.\n"
        "- `record_score` attaches the verdict to the run's own Langfuse trace. Silent no-op\n"
        "  when tracing is off."
    ),
    code(
        "from pydantic import BaseModel\n"
        "\n"
        "\n"
        "class Verdict(BaseModel):\n"
        "    verified: bool\n"
        "    reason: str\n"
        "\n"
        "\n"
        "JUDGE_PROMPT = (\n"
        "    \"You are auditing one run of an inspection copilot against the database record.\\n\"\n"
        "    \"Mark verified=true if ALL of these hold:\\n\"\n"
        "    \"  (a) the trajectory shows the copilot did what the task required (searched history\\n\"\n"
        "    \"      before recording; recorded a finding when the task asked for one);\\n\"\n"
        "    \"  (b) every database write it claims is confirmed by the evidence below;\\n\"\n"
        "    \"  (c) every finding_id cited in the final answer appears in the evidence as EXISTS;\\n\"\n"
        "    \"  (d) the final answer does not contradict the trajectory or invent database records.\\n\"\n"
        "    \"Interpretive judgement (severity reasoning, recommendations, comparisons phrased as\\n\"\n"
        "    \"the copilot's own assessment) is allowed and does NOT fail the audit. Fabricated\\n\"\n"
        "    \"records, fabricated finding_ids, or claims of actions absent from the trajectory DO\\n\"\n"
        "    \"fail it.\\n\\n\"\n"
        "    \"# Task\\n{task}\\n\\n# Trajectory\\n{trajectory}\\n\\n# Final answer\\n{answer}\\n\\n\"\n"
        "    \"# Database evidence\\n{evidence}\"\n"
        ")\n"
        "\n"
        "\n"
        "def build_evidence(answer):\n"
        "    \"\"\"Ground truth for the judge: re-query every finding_id the answer names - the\n"
        "    one it recorded plus any priors it cites - and mark each EXISTS / NOT FOUND. This\n"
        "    is the deterministic floor that catches a confident answer citing a record that\n"
        "    does not exist. It is plain SQL, run before the judge sees anything.\"\"\"\n"
        "    import re\n"
        "    lines = []\n"
        "    for fid in sorted(set(re.findall(r\"\\b[0-9a-f]{8}-[0-9a-f]{3}\\b\", answer))):\n"
        "        with conn.cursor() as cur:\n"
        "            cur.execute(\"\"\"SELECT asset_id, category, severity FROM CITY_INSPECTION_FINDING\n"
        "                           WHERE finding_id = :f\"\"\", f=fid)\n"
        "            row = cur.fetchone()\n"
        "        if row:\n"
        "            lines.append(f\"finding {fid} EXISTS: asset={row[0]} category={row[1]} severity={row[2]}\")\n"
        "        else:\n"
        "            lines.append(f\"finding {fid} NOT FOUND in CITY_INSPECTION_FINDING\")\n"
        "    return \"\\n\".join(lines) or \"(no findings cited in the answer)\"\n"
        "\n"
        "\n"
        "_judge_model = CHAT.with_structured_output(Verdict)\n"
        "\n"
        "\n"
        "def judge_workflow(task: str, run: dict) -> Verdict:\n"
        "    prompt = JUDGE_PROMPT.format(\n"
        "        task=task,\n"
        "        trajectory=improve.trajectory_to_text(run[\"trajectory\"]),\n"
        "        answer=run[\"answer\"],\n"
        "        evidence=build_evidence(run[\"answer\"]),\n"
        "    )\n"
        "    cfg = {\"callbacks\": [HANDLER]} if HANDLER else {}\n"
        "    return _judge_model.invoke(prompt, config=cfg)\n"
        "\n"
        "\n"
        "def record_score(name: str, value: float, comment: str = \"\", trace_id: str | None = None):\n"
        "    \"\"\"Log a verdict as a Langfuse score, attached to the run's own trace so it is\n"
        "    not orphaned. When `trace_id` is given (the id of the trace opened by\n"
        "    run_and_learn's span, see Section 6) it is passed straight to create_score;\n"
        "    otherwise falls back to scoring whatever trace is currently active. Silently\n"
        "    no-ops when tracing is off.\"\"\"\n"
        "    if HANDLER is None:\n"
        "        return\n"
        "    try:\n"
        "        from langfuse import get_client\n"
        "        client = get_client()\n"
        "        if trace_id is not None:\n"
        "            client.create_score(trace_id=trace_id, name=name, value=value, comment=comment)\n"
        "        else:\n"
        "            client.score_current_trace(name=name, value=value, comment=comment)\n"
        "        client.flush()\n"
        "    except Exception as e:\n"
        "        print(f\"(langfuse score skipped: {e})\")\n"
        "\n"
        "ok(\"judge ready\")"
    ),
]

# --------------------------------------------------------------------------
# Section: workflow capture with gray-band dedup
# --------------------------------------------------------------------------
CAPTURE = [
    md(
        "## 6 · Workflow capture: dedup by meaning, with an honest gray band\n\n"
        "A fixed 0.15 cosine cutoff under-merges paraphrases and over-merges neighbours.\n"
        "Here distances split three ways: certain merge, certain new, and a **gray band**\n"
        "where a cheap LLM call answers 'same task?' before counts are polluted.\n\n"
        "One residual limitation stays open, on purpose: a phrasing beyond the `new` boundary\n"
        "still splits silently - the gray band narrows the failure mode, it does not eliminate\n"
        "it. Notebook 04's evals measure how often that actually happens."
    ),
    md(
        "**Fold this run into an existing workflow, or start a new one.** Nearest-neighbour\n"
        "on the intent embedding, then `merge_decision` splits three ways: merge below 0.15,\n"
        "new above 0.40, and an LLM same-task check for the band between.\n\n"
        "- Only a **verified** run increments `verified_successes`; an unverified one\n"
        "  increments `failures`. That is what stops a repeatedly-failing task from being\n"
        "  harvested.\n"
        "- On merge, `steps` is overwritten with the latest verified trajectory - the one §7\n"
        "  will distil.\n"
        "- `run_and_learn` is the full cycle: act → judge → score → capture → feed skill\n"
        "  outcomes, all inside one trace."
    ),
    code(
        "class SameTask(BaseModel):\n"
        "    same: bool\n"
        "\n"
        "\n"
        "_same_task_model = CHAT.with_structured_output(SameTask)\n"
        "\n"
        "\n"
        "def _nearest_workflow(intent_vec):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT workflow_id, intent,\n"
        "                              VECTOR_DISTANCE(intent_embedding, :q, COSINE) AS distance\n"
        "                         FROM HARNESS_WORKFLOW ORDER BY distance FETCH FIRST 1 ROWS ONLY\"\"\",\n"
        "                    q=intent_vec)\n"
        "        row = cur.fetchone()\n"
        "    if row is None:\n"
        "        return None\n"
        "    return {\"workflow_id\": row[0],\n"
        "            \"intent\": row[1].read() if hasattr(row[1], \"read\") else row[1],\n"
        "            \"distance\": row[2]}\n"
        "\n"
        "\n"
        "def capture_workflow(intent: str, run: dict, verified: bool) -> str:\n"
        "    intent_vec = array.array('f', embedder.embed([intent])[0].tolist())\n"
        "    nearest = _nearest_workflow(intent_vec)\n"
        "    decision = \"new\"\n"
        "    if nearest is not None:\n"
        "        # ✏️ TODO(3): decide merge/new. Use improve.merge_decision(nearest['distance']);\n"
        "        #             on 'ask', confirm with the LLM: are `intent` and `nearest['intent']`\n"
        "        #             the same recurring task? (_same_task_model.invoke(...).same)\n"
        "        # TODO-SOLUTION-START\n"
        "        decision = improve.merge_decision(nearest[\"distance\"])\n"
        "        if decision == \"ask\":\n"
        "            q = (f\"Task A: {intent}\\nTask B: {nearest['intent']}\\n\"\n"
        "                 \"Are these the same recurring task type (same procedure, possibly \"\n"
        "                 \"different asset)? Answer same=true/false.\")\n"
        "            decision = \"merge\" if _same_task_model.invoke(q).same else \"new\"\n"
        "        # TODO-SOLUTION-END\n"
        "    if decision == \"merge\":\n"
        "        wid = nearest[\"workflow_id\"]\n"
        "        with conn.cursor() as cur:\n"
        "            # ✏️ TODO(4): only a VERIFIED run may increment verified_successes; an\n"
        "            #             unverified run increments failures. Update occurrences,\n"
        "            #             the right counter, steps (latest verified trajectory), last_seen.\n"
        "            # TODO-SOLUTION-START\n"
        "            if verified:\n"
        "                cur.execute(\"\"\"UPDATE HARNESS_WORKFLOW\n"
        "                               SET occurrences = occurrences + 1,\n"
        "                                   verified_successes = verified_successes + 1,\n"
        "                                   steps = :s, intent_embedding = :e,\n"
        "                                   last_seen = CURRENT_TIMESTAMP\n"
        "                             WHERE workflow_id = :w\"\"\",\n"
        "                            s=json.dumps(run[\"trajectory\"], default=str), e=intent_vec, w=wid)\n"
        "            else:\n"
        "                cur.execute(\"\"\"UPDATE HARNESS_WORKFLOW\n"
        "                               SET occurrences = occurrences + 1,\n"
        "                                   failures = failures + 1,\n"
        "                                   intent_embedding = :e,\n"
        "                                   last_seen = CURRENT_TIMESTAMP\n"
        "                             WHERE workflow_id = :w\"\"\", e=intent_vec, w=wid)\n"
        "            # TODO-SOLUTION-END\n"
        "        conn.commit()\n"
        "        return wid\n"
        "    wid = str(uuid.uuid4())[:12]\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"INSERT INTO HARNESS_WORKFLOW\n"
        "                       (workflow_id, intent, intent_embedding, steps, tools_used,\n"
        "                        verified_successes, failures)\n"
        "                       VALUES (:w, :i, :e, :s, :t, :vs, :f)\"\"\",\n"
        "                    w=wid, i=intent, e=intent_vec,\n"
        "                    s=json.dumps(run[\"trajectory\"], default=str),\n"
        "                    t=\",\".join(sorted({s[\"tool\"] for s in run[\"trajectory\"]})),\n"
        "                    vs=1 if verified else 0, f=0 if verified else 1)\n"
        "    conn.commit()\n"
        "    return wid\n"
        "\n"
        "\n"
        "def _act_and_judge(task: str, **kwargs):\n"
        "    \"\"\"One act -> judge attempt inside a single Langfuse span, so every model call\n"
        "    lands as a child observation and the verdict score is attached to that same\n"
        "    trace (langfuse==4.14.1's LangchainCallbackHandler has no trace-id hook;\n"
        "    start_as_current_observation()/score_current_trace() is what the SDK exposes).\"\"\"\n"
        "    if HANDLER is not None:\n"
        "        from langfuse import get_client\n"
        "        with get_client().start_as_current_observation(\n"
        "            name=\"run_and_learn\", as_type=\"span\"\n"
        "        ) as _span:\n"
        "            tid = _span.trace_id\n"
        "            run = run_copilot_task(task, **kwargs)\n"
        "            verdict = judge_workflow(task, run)\n"
        "            record_score(\"workflow_verified\", 1.0 if verdict.verified else 0.0,\n"
        "                         verdict.reason, trace_id=tid)\n"
        "    else:\n"
        "        run = run_copilot_task(task, **kwargs)\n"
        "        verdict = judge_workflow(task, run)\n"
        "        record_score(\"workflow_verified\", 1.0 if verdict.verified else 0.0, verdict.reason)\n"
        "    return run, verdict\n"
        "\n"
        "\n"
        "def run_and_learn(task: str, *, max_tries: int = 1, **kwargs) -> dict:\n"
        "    \"\"\"Act -> judge -> capture -> update skill outcomes. Agent behaviour is\n"
        "    stochastic (it sometimes skips the record step or cites an unconfirmed\n"
        "    finding_id, which the judge correctly rejects), so a teaching arc that needs a\n"
        "    verified run retries up to `max_tries` rather than gambling on a clean one.\n"
        "    Only the FINAL attempt is captured, so retries never pollute the counters.\"\"\"\n"
        "    for attempt in range(1, max_tries + 1):\n"
        "        run, verdict = _act_and_judge(task, **kwargs)\n"
        "        if verdict.verified or attempt == max_tries:\n"
        "            break\n"
        "        print(f\"  (attempt {attempt} unverified, retrying: {verdict.reason[:70]})\")\n"
        "    wid = capture_workflow(task, run, verdict.verified)\n"
        "    update_skill_outcomes(run[\"skill_ids\"], verdict.verified)\n"
        "    print(f\"verified={verdict.verified} workflow={wid}\\n  judge: {verdict.reason[:140]}\")\n"
        "    return {\"run\": run, \"verdict\": verdict, \"workflow_id\": wid}\n"
        "\n"
        "\n"
        "def update_skill_outcomes(skill_ids, verified):  # redefined in Section 7\n"
        "    pass\n"
        "\n"
        "ok(\"capture pipeline ready\")"
    ),
]

# --------------------------------------------------------------------------
# Section: harvester + skill lifecycle + two-level retrieval
# --------------------------------------------------------------------------
SKILLS_SEC = [
    md(
        "## 7 · Harvesting skills - and making them earn their authority\n\n"
        "The harvester promotes workflows that **recur and verifiably work** into `SKILL.md`\n"
        "documents. Three review fixes land here:\n\n"
        "- distillation reads the **full trajectory** (args + results), then a **faithfulness\n"
        "  check** compares the distilled steps back against it - unfaithful skills are rejected\n"
        "- a new skill is born **provisional** (low prompt authority), not trusted on creation\n"
        "- retrieval applies a **distance threshold** and injects **approved before provisional**"
    ),
    md(
        "**Distil a recurring workflow into a `SKILL.md` - if it earns it.** `harvest_ready`\n"
        "gates on three signals at once: at least 3 occurrences, at least 2 verified\n"
        "successes, and more successes than failures.\n\n"
        "- Distillation reads the **full trajectory** (args and results), not a set of tool\n"
        "  names, so the procedure can be grounded in what actually happened.\n"
        "- A second model call checks the distilled steps back against that trajectory;\n"
        "  unfaithful output is rejected and nothing is written.\n"
        "- Every skill is born `provisional`. Promotion is earned later, in §8."
    ),
    code(
        "class Distilled(BaseModel):\n"
        "    name: str\n"
        "    description: str\n"
        "    when_to_use: str\n"
        "    steps_body: str\n"
        "\n"
        "\n"
        "class Faithful(BaseModel):\n"
        "    faithful: bool\n"
        "    reason: str\n"
        "\n"
        "\n"
        "_distill_model = CHAT.with_structured_output(Distilled)\n"
        "_faithful_model = CHAT.with_structured_output(Faithful)\n"
        "\n"
        "\n"
        "def promote_workflow_to_skill(row) -> str | None:\n"
        "    # open_capability is harness plumbing (how tools get loaded), not a domain\n"
        "    # step - a reusable skill distills the actual work, so drop it first.\n"
        "    domain_steps = [s for s in json.loads(row[\"steps\"]) if s[\"tool\"] != \"open_capability\"]\n"
        "    steps_text = improve.trajectory_to_text(domain_steps)\n"
        "    d = _distill_model.invoke(\n"
        "        \"Distill this verified, recurring copilot trajectory into a reusable procedure.\\n\"\n"
        "        \"Ground every step in what ACTUALLY happened - name the tools used, in order,\\n\"\n"
        "        \"with parameterised arguments. Do not invent steps.\\n\\n\"\n"
        "        f\"Intent: {row['intent']}\\n\\nTrajectory:\\n{steps_text}\"\n"
        "    )\n"
        "    f = _faithful_model.invoke(\n"
        "        \"Do these distilled steps faithfully describe this trajectory - same tools, same\\n\"\n"
        "        \"order, no invented actions? faithful=true/false.\\n\\n\"\n"
        "        f\"Distilled steps:\\n{d.steps_body}\\n\\nTrajectory:\\n{steps_text}\"\n"
        "    )\n"
        "    if not f.faithful:\n"
        "        print(f\"  REJECTED (unfaithful distillation): {f.reason[:120]}\")\n"
        "        return None\n"
        "    tools_used = sorted({s['tool'] for s in domain_steps})\n"
        "    content = improve.render_skill_md(\n"
        "        name=d.name, description=d.description, tools=tools_used,\n"
        "        when_to_use=d.when_to_use, steps_body=d.steps_body,\n"
        "        source_workflow_id=row[\"workflow_id\"])\n"
        "    import hashlib\n"
        "    sha = hashlib.sha256(content.encode()).hexdigest()\n"
        "    sid = str(uuid.uuid4())[:12]\n"
        "    vec = array.array('f', embedder.embed([f\"{d.name}: {d.description}\"])[0].tolist())\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"INSERT INTO HARNESS_SKILLS\n"
        "                       (skill_id, name, description, content, sha, status,\n"
        "                        source_workflow_id, embedding)\n"
        "                       VALUES (:sid, :n, :d, :c, :sha, 'provisional', :src, :e)\"\"\",\n"
        "                    sid=sid, n=d.name, d=d.description, c=content, sha=sha,\n"
        "                    src=row[\"workflow_id\"], e=vec)\n"
        "        cur.execute(\"UPDATE HARNESS_WORKFLOW SET promoted = 'Y' WHERE workflow_id = :w\",\n"
        "                    w=row[\"workflow_id\"])\n"
        "    conn.commit()\n"
        "    print(f\"  harvested PROVISIONAL skill {d.name!r} ({sid}) from workflow {row['workflow_id']}\")\n"
        "    return sid\n"
        "\n"
        "\n"
        "def harvest() -> list:\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT workflow_id, intent, steps, occurrences,\n"
        "                              verified_successes, failures\n"
        "                         FROM HARNESS_WORKFLOW WHERE promoted = 'N'\"\"\")\n"
        "        cols = [d[0].lower() for d in cur.description]\n"
        "        rows = []\n"
        "        for r in cur.fetchall():\n"
        "            row = dict(zip(cols, r))\n"
        "            if hasattr(row[\"steps\"], \"read\"):\n"
        "                row[\"steps\"] = row[\"steps\"].read()\n"
        "            if hasattr(row[\"intent\"], \"read\"):\n"
        "                row[\"intent\"] = row[\"intent\"].read()\n"
        "            rows.append(row)\n"
        "    harvested = []\n"
        "    for row in rows:\n"
        "        # ✏️ TODO(5): the harvest gate - promote only what recurs AND verifiably works.\n"
        "        #             Use improve.harvest_ready(occurrences, verified_successes, failures).\n"
        "        # TODO-SOLUTION-START\n"
        "        if not improve.harvest_ready(row[\"occurrences\"], row[\"verified_successes\"],\n"
        "                                     row[\"failures\"]):\n"
        "            continue\n"
        "        # TODO-SOLUTION-END\n"
        "        sid = promote_workflow_to_skill(row)\n"
        "        if sid:\n"
        "            harvested.append(sid)\n"
        "    return harvested\n"
        "\n"
        "ok(\"harvester ready\")"
    ),
    md(
        "**Two-level retrieval, and the loop that finally closes.** `retrieve_skills` cuts at\n"
        "`SKILL_DISTANCE_MAX`; `build_skill_manifest` sorts approved ahead of provisional and\n"
        "labels each with the authority it has actually earned.\n\n"
        "- An approved skill is introduced as \"prefer this approach\"; a provisional one as an\n"
        "  unproven candidate to verify. Same retrieval, different prompt authority.\n"
        "- `update_skill_outcomes` feeds each run's verdict back to the skills that run used,\n"
        "  then `lifecycle_transition` applies it: approved at 2 verified successes with zero\n"
        "  failures, retired at 2 failures."
    ),
    code(
        "# Skills still use similarity retrieval (unlike tools, which moved to capability\n"
        "# disclosure): measured live, a task phrased differently from the skill's distilled\n"
        "# tight cutoff (observed 0.559 for a genuinely matching task at 0.55), while an\n"
        "# off-topic query sits far away (observed >=1.0). 0.65 keeps a wide margin both\n"
        "# ways.\n"
        "SKILL_DISTANCE_MAX = 0.65\n"
        "\n"
        "\n"
        "def retrieve_skills(query: str, k: int = 3):\n"
        "    qv = array.array('f', embedder.embed([query])[0].tolist())\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT skill_id, name, status, content,\n"
        "                              VECTOR_DISTANCE(embedding, :q, COSINE) AS distance\n"
        "                         FROM HARNESS_SKILLS WHERE status != 'retired'\n"
        "                        ORDER BY distance FETCH FIRST :k ROWS ONLY\"\"\", q=qv, k=k)\n"
        "        cols = [d[0].lower() for d in cur.description]\n"
        "        rows = []\n"
        "        for r in cur.fetchall():\n"
        "            row = dict(zip(cols, r))\n"
        "            if hasattr(row[\"content\"], \"read\"):\n"
        "                row[\"content\"] = row[\"content\"].read()\n"
        "            rows.append(row)\n"
        "    return improve.filter_by_distance(rows, SKILL_DISTANCE_MAX)\n"
        "\n"
        "\n"
        "def build_skill_manifest(query):\n"
        "    \"\"\"Two-level retrieval: approved skills carry authority; provisional ones are\n"
        "    labelled as unproven candidates to verify.\"\"\"\n"
        "    hits = retrieve_skills(query)\n"
        "    if not hits:\n"
        "        return \"\", []\n"
        "    parts, ids = [], []\n"
        "    for h in sorted(hits, key=lambda r: 0 if r[\"status\"] == \"approved\" else 1):\n"
        "        ids.append(h[\"skill_id\"])\n"
        "        if h[\"status\"] == \"approved\":\n"
        "            label = \"APPROVED procedure - prefer this approach:\"\n"
        "        else:\n"
        "            label = (\"PROVISIONAL procedure - an unproven candidate; treat as a\"\n"
        "                     \" suggestion and verify against fresh data:\")\n"
        "        parts.append(f\"\\n\\n--- {label} ---\\n{h['content']}\")\n"
        "    return \"\".join(parts), ids\n"
        "\n"
        "\n"
        "def update_skill_outcomes(skill_ids, verified):\n"
        "    \"\"\"Close the loop the review said never closes: runs that used a skill feed the\n"
        "    skill's own record, and the lifecycle transition runs on the new counts.\"\"\"\n"
        "    for sid in skill_ids:\n"
        "        with conn.cursor() as cur:\n"
        "            cur.execute(\"\"\"UPDATE HARNESS_SKILLS SET uses = uses + 1,\n"
        "                           verified_successes = verified_successes + :vs,\n"
        "                           failures = failures + :f, updated_at = CURRENT_TIMESTAMP\n"
        "                         WHERE skill_id = :sid\"\"\",\n"
        "                        vs=1 if verified else 0, f=0 if verified else 1, sid=sid)\n"
        "            cur.execute(\"\"\"SELECT status, verified_successes, failures\n"
        "                             FROM HARNESS_SKILLS WHERE skill_id = :sid\"\"\", sid=sid)\n"
        "            status, vs, fl = cur.fetchone()\n"
        "            new_status = improve.lifecycle_transition(status, vs, fl)\n"
        "            if new_status != status:\n"
        "                cur.execute(\"UPDATE HARNESS_SKILLS SET status = :s WHERE skill_id = :sid\",\n"
        "                            s=new_status, sid=sid)\n"
        "                print(f\"  skill {sid}: {status} -> {new_status}\")\n"
        "        conn.commit()\n"
        "\n"
        "ok(\"skill retrieval + lifecycle ready\")"
    ),
]

# --------------------------------------------------------------------------
# Section: the demo arc
# --------------------------------------------------------------------------
DEMO = [
    md(
        "## 8 · The arc: recur → verify → harvest → earn approval\n\n"
        "Three inspectors phrase the same corrosion-triage task differently. Watch the gray\n"
        "band merge them, the judge verify them, and the harvester fire at three verified\n"
        "occurrences. Then a fourth task *uses* the provisional skill - and its verified\n"
        "outcomes promote it to approved."
    ),
    md(
        "**Follow one workflow through the whole arc.** `show_registries` prints *everything*;\n"
        "`follow_workflow` tracks the **single** workflow this task creates - its counters\n"
        "climbing toward the harvest gate, then the skill it spawns being born and promoted.\n"
        "Watch the `PEA` line under each snapshot."
    ),
    code(
        "def follow_workflow(wid, stage):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"\"\"SELECT occurrences, verified_successes, failures, promoted\n"
        "                       FROM HARNESS_WORKFLOW WHERE workflow_id = :w\"\"\", w=wid)\n"
        "        w = cur.fetchone()\n"
        "        cur.execute(\"\"\"SELECT name, status, uses, verified_successes FROM HARNESS_SKILLS\n"
        "                       WHERE source_workflow_id = :w\n"
        "                       ORDER BY created_at FETCH FIRST 1 ROWS ONLY\"\"\", w=wid)\n"
        "        s = cur.fetchone()\n"
        "    occ, vs, fa, pr = w\n"
        "    gate = \"HARVEST-READY\" if (occ >= 3 and vs >= 2 and vs > fa) else f\"{occ}/3 to gate\"\n"
        "    skill = f\"skill '{s[0]}' [{s[1]}] uses={s[2]} verified={s[3]}\" if s else \"(no skill yet)\"\n"
        "    print(f\"  PEA {wid[:6]} | {stage:26} | occ={occ} verified={vs} fail={fa} \"\n"
        "          f\"promoted={pr} | {gate} | {skill}\")\n"
        "\n"
        "ok(\"follow_workflow lens ready - the PEA line follows one workflow\")"
    ),
    md(
        "**Occurrence 1 - the unaided baseline.**\n"
        "*What this `run_and_learn` does:* acts with no skill help (`use_skills=False`), the\n"
        "judge verifies, and CAPTURE finds an empty table so it **inserts a new workflow**.\n"
        "*Look for:* a brand-new `HARNESS_WORKFLOW` row, and the `PEA` line reading `occ=1\n"
        "verified=1 promoted=N | 1/3 to gate` - one run is an episode, not yet a pattern."
    ),
    code(
        "print(f\"=== Occurrence 1 ({ASSET_A}) ===\")\n"
        "r1 = run_and_learn(\n"
        "    f\"Inspect {ASSET_A}: heavy corrosion on the bearing plates at pier 2. Assess severity\"\n"
        "    \" against past findings and record a finding with your recommendation.\",\n"
        "    use_skills=False, max_tries=3)\n"
        "WID = r1[\"workflow_id\"]   # the pea we will follow all the way to an approved skill"
    ),
    md(
        "**Registry check.** First workflow row, `occurrences=1`, `verified=1`, `promoted=N`.\n"
        "`HARNESS_SKILLS` is still empty - one run is an episode, not a pattern."
    ),
    code("show_registries(\"after occurrence 1\")\nfollow_workflow(WID, \"after occ 1\")"),
    md(
        "**Occurrence 2 - the same task, reworded.**\n"
        "*What this `run_and_learn` does:* same task in different words; CAPTURE embeds it,\n"
        "finds occurrence 1 as nearest, and `merge_decision` (distance `<0.15`, or the gray\n"
        "band's LLM saying \"same task\") **merges** instead of inserting.\n"
        "*Look for:* the `PEA` line's workflow id **unchanged** and `occ=2` - one row, not two.\n"
        "A second row here would be the silent split §6 admits it only narrows."
    ),
    code(
        "print(f\"=== Occurrence 2 ({ASSET_A}, new phrasing) ===\")\n"
        "r2 = run_and_learn(\n"
        "    f\"Corrosion check on {ASSET_A} bearings - compare with prior reports and log what\"\n"
        "    \" you find with a recommendation.\",\n"
        "    inspector=\"T_Vance\", use_skills=False, max_tries=3)"
    ),
    md(
        "**Registry check - the merge.** Still **one** row, now `occurrences=2`. Same\n"
        "`workflow_id` as the last check means the reworded task was recognised as the same\n"
        "recurring task. A second row here would be the silent split."
    ),
    code("show_registries(\"after occurrence 2 - merged, not split\")\nfollow_workflow(WID, \"after occ 2 (merged)\")"),
    md(
        "**Occurrence 3 - same task type, different asset.**\n"
        "*What this `run_and_learn` does:* the hard merge. A *different asset* pushes the\n"
        "distance up so it lands in the **gray band** - distance alone can't settle it, so the\n"
        "LLM is asked whether \"same procedure, different asset\" is the same recurring task.\n"
        "*Look for:* still **one** row, `PEA` reading `occ=3 verified=3 | HARVEST-READY` - the\n"
        "third verified occurrence is exactly what clears the gate in the next cell."
    ),
    code(
        "print(f\"=== Occurrence 3 ({ASSET_B}, same task type, different asset) ===\")\n"
        "r3 = run_and_learn(\n"
        "    f\"Inspect {ASSET_B}: surface rust and section loss on the bearing members. Assess\"\n"
        "    \" severity against past findings and record a finding with your recommendation.\",\n"
        "    inspector=\"K_Osei\", use_skills=False, max_tries=3)"
    ),
    md(
        "**The registry after three runs.** One row - `occurrences=3`,\n"
        "`verified_successes=3`, `failures=0`, `promoted='N'` - which is exactly what clears\n"
        "the harvest gate on the next cell."
    ),
    code("show_registries(\"after 3 occurrences - the harvest gate is now satisfied\")\nfollow_workflow(WID, \"after occ 3\")"),
    md(
        "**Harvest.** Not a `run_and_learn` - this is `harvest()`, the promotion step.\n"
        "*What it does:* the gate (`occ>=3 AND verified>=2 AND verified>failures`) passes, the\n"
        "stored trajectory is distilled into a `SKILL.md`, a second model call checks the\n"
        "distilled steps are faithful to the trajectory, and the skill is written `provisional`.\n"
        "*Look for:* the `PEA` line flip to `promoted=Y` with a skill name appearing - the\n"
        "workflow becomes a reusable skill, born unproven."
    ),
    code(
        "print(\"=== Harvest ===\")\n"
        "new_skills = harvest()\n"
        "check(len(new_skills) >= 1, f\"harvested {len(new_skills)} provisional skill(s)\")"
    ),
    md(
        "**Registry check - the phase change.** Two things moved at once: the workflow's\n"
        "`promoted` flipped to `Y` (so it is never harvested twice), and the first\n"
        "`HARNESS_SKILLS` row appeared as `provisional` with `uses=0`."
    ),
    code("show_registries(\"after harvest - workflow promoted, skill born provisional\")\nfollow_workflow(WID, \"after harvest\")"),
    md(
        "**The distilled artifact.** Read the frontmatter as provenance: `tools` lists what\n"
        "actually ran, and `source_workflow` points back at the evidence it came from."
    ),
    code(
        "# Show the distilled SKILL.md - grounded in the real trajectory, not confabulated.\n"
        "with conn.cursor() as cur:\n"
        "    cur.execute(\"SELECT content FROM HARNESS_SKILLS FETCH FIRST 1 ROWS ONLY\")\n"
        "    _content = cur.fetchone()[0]\n"
        "print(_content.read() if hasattr(_content, 'read') else _content)"
    ),
    md(
        "**First use of the provisional skill.**\n"
        "*What this `run_and_learn` does:* `use_skills=True` (the default), so STEP 2 now finds\n"
        "the harvested skill within distance and injects it (labelled *unproven*). The run's\n"
        "verdict flows back to that skill via `update_skill_outcomes` (STEP 6).\n"
        "*Look for:* the `PEA` skill line gaining `uses=1`; the `check` confirms the skill was\n"
        "actually retrieved (`skill_ids` non-empty). Status stays `provisional` - one isn't two."
    ),
    code(
        "print(f\"=== Using the provisional skill (run 1) ===\")\n"
        "r4 = run_and_learn(\n"
        "    f\"New corrosion report on {ASSET_A}'s pier-2 bearing plates - triage it against\"\n"
        "    f\" history and record a finding with your recommendation.\",\n"
        "    inspector=\"J_Ibarra\", max_tries=3)\n"
        "check(len(r4[\"run\"][\"skill_ids\"]) >= 1, \"provisional skill was retrieved and used\")"
    ),
    md(
        "**Registry check - outcomes flow back.** The skill's `uses` ticks up, and `verified`\n"
        "with it *if that run was judged verified*: the run that consumed the skill fed its own\n"
        "verdict back into the skill's record. Status stays `provisional` - promotion needs\n"
        "**two verified** uses. Watch the `PEA` line for the real counts."
    ),
    code("show_registries(\"after skill use 1 - counters moving, still provisional\")\nfollow_workflow(WID, \"after skill use 1\")"),
    md(
        "**Second use - promotion fires once two uses verify.**\n"
        "*What this `run_and_learn` does:* uses the skill again and feeds back another verdict.\n"
        "When the skill reaches **two verified uses, zero failures**, `lifecycle_transition`\n"
        "flips it `provisional → approved` - authority earned by linked outcomes, not granted\n"
        "at creation (the loop the review said never closes).\n"
        "*Look for:* the `PEA` skill line - `[approved]` if both uses verified, still\n"
        "`[provisional]` if one didn't (verification is stochastic; a skill *staying*\n"
        "provisional is the gate holding, not a bug)."
    ),
    code(
        "print(f\"=== Using the skill again (run 2) - promotion happens here if both verified ===\")\n"
        "r5 = run_and_learn(\n"
        "    f\"{ASSET_B}: corrosion on the bearing members - check history, then record a\"\n"
        "    f\" finding with a recommendation.\",\n"
        "    inspector=\"R_Mercer\", max_tries=3)"
    ),
    md(
        "**Registry check - authority earned (or the gate holding).** With two verified uses\n"
        "and zero failures the `status` reads **approved** - and nothing approved it except its\n"
        "own track record. If one use failed to verify even after retries, the `PEA` still\n"
        "reads `provisional`: honest, and exactly the point - authority is earned, never\n"
        "assumed.\n\n"
        "Either way, compare against the baseline snapshot in §2: every row on screen was\n"
        "written by the harness while you ran the notebook."
    ),
    code("show_registries(\"after skill use 2 - provisional -> approved\")\nfollow_workflow(WID, \"after skill use 2\")"),
    md(
        "**The threshold, proved negatively.** An off-topic query returns an empty manifest.\n"
        "Retrieval that injects *nothing* is the whole point of the distance cutoff - the\n"
        "alternative is top-k always finding something."
    ),
    code(
        "# Retrieval thresholds in action: an off-topic task injects NO skills, no tools.\n"
        "manifest, ids = build_skill_manifest(\"plan the office holiday party\")\n"
        "check(manifest == \"\" and ids == [], \"off-topic query injects no skills\")"
    ),
]

# --------------------------------------------------------------------------
# Section: closing
# --------------------------------------------------------------------------
CLOSING = [
    md(
        "## 9 · What you built (vs. what the review criticised)\n\n"
        "| Review gap | This notebook |\n"
        "|---|---|\n"
        "| Trajectory = sorted set of tool names | Ordered steps with args + truncated results |\n"
        "| `success = bool(final)` | LLM judge audits trajectory **and database evidence** |\n"
        "| Brittle 0.15 dedup cutoff | Gray band + LLM same-task confirmation |\n"
        "| One-way promotion, max authority | Provisional → approved/retired via linked outcomes |\n"
        "| Unconditional top-k injection | Capability disclosure for tools; distance threshold for skills |\n\n"
        "Next: **02 - Scheduled briefings**, where the *other* promotion path (scratch →\n"
        "long-term memory) gets the same treatment: opt-in curation, provenance, supersession,\n"
        "and a consumer that is actually scheduled."
    ),
    md(
        "**Cross-notebook state check.** Asserts that the artifacts notebook 02 depends on are\n"
        "actually in place, so a broken hand-off fails here rather than three notebooks later."
    ),
    code(
        "for desc, passed in verify(conn, \"01_self_improving_copilot\"):\n"
        "    check(passed, desc)\n"
        "ok(\"notebook 01 artifacts in place - continue to 02_scheduled_briefings\")"
    ),
]

# --------------------------------------------------------------------------
# Section: closing the loop - the copilot as a memory producer
# --------------------------------------------------------------------------
PRODUCER = [
    md(
        "## 8b · Closing the loop: the copilot as a memory *producer*\n\n"
        "So far the copilot records **findings** (into `CITY_INSPECTION_FINDING`) and learns\n"
        "**skills**. What it does *not* yet do is decide what is worth *remembering* - the\n"
        "scratch notes that notebook 02's promotion pipeline curates. Notebook 02 hand-seeds\n"
        "those notes; here is where they would really come from.\n\n"
        "The design choice worth noticing: the agent is **never told about directories**. It\n"
        "gets one `remember(asset_id, note, durable)` tool and judges only *is this worth\n"
        "keeping?*. The **tool** owns the convention - `durable=True` files to `/inbox` (the\n"
        "opt-in area notebook 02 promotes from), `durable=False` to `/work` (scratch, never\n"
        "promoted). Placement is policy; the agent only supplies judgement."
    ),
    md(
        "**The `remember` tool.** Backed by the same `HARNESS_SCRATCH` schema notebook 02\n"
        "reads (created here if absent), so a note filed by this copilot is a note that\n"
        "notebook's pipeline can pick up unchanged. The path is derived, never chosen by the\n"
        "model."
    ),
    code(
        "import re\n"
        "from cityops_harness import promote\n"
        "from langchain_core.tools import tool\n"
        "\n"
        "with conn.cursor() as cur:\n"
        "    try:\n"
        "        cur.execute(\"\"\"CREATE TABLE HARNESS_SCRATCH (\n"
        "            path       VARCHAR2(512) PRIMARY KEY,\n"
        "            content    CLOB NOT NULL,\n"
        "            revision   VARCHAR2(64) NOT NULL,\n"
        "            status     VARCHAR2(1) DEFAULT 'N'\n"
        "                       CHECK (status IN ('N','S','P','D','H')),\n"
        "            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\"\"\")\n"
        "    except Exception as e:\n"
        "        if \"ORA-00955\" not in str(e):   # 'name already used' = already there\n"
        "            raise\n"
        "\n"
        "\n"
        "def _slug(text):\n"
        "    return re.sub(r\"[^a-z0-9]+\", \"-\", text.lower()).strip(\"-\")[:40] or \"note\"\n"
        "\n"
        "\n"
        "@tool\n"
        "def remember(asset_id: str, note: str, durable: bool) -> str:\n"
        "    \"\"\"File a note for long-term memory curation.\n"
        "    durable=True  -> a completed, keep-worthy finding (enters the promotion inbox).\n"
        "    durable=False -> scratch reasoning or a dead end (kept OUT of long-term memory).\n"
        "    Returns the path it was filed under. You never choose the path.\"\"\"\n"
        "    path = f\"/inbox/{asset_id}/{_slug(note)}.md\" if durable else f\"/work/{_slug(note)}.md\"\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(\"DELETE FROM HARNESS_SCRATCH WHERE path = :p\", p=path)\n"
        "        cur.execute(\"INSERT INTO HARNESS_SCRATCH (path, content, revision) \"\n"
        "                    \"VALUES (:p, :c, :r)\", p=path, c=note, r=promote.note_revision(note))\n"
        "    conn.commit()\n"
        "    return path\n"
        "\n"
        "ok(\"remember() ready - the tool owns placement; the agent only judges durable vs not\")"
    ),
    md(
        "**Run the producer.** The copilot gets its usual tools *plus* `remember`, and a prompt\n"
        "that asks it to keep durable findings and discard scratch - in those words, not in\n"
        "directory names. Watch the `remember(... durable=True/False ...)` calls: the model\n"
        "decides worth, the tool decides where."
    ),
    code(
        "from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage\n"
        "\n"
        "PRODUCER_PROMPT = (\n"
        "    \"You are the CityOps inspection copilot, now also responsible for what gets\\n\"\n"
        "    \"remembered. Do the task through your tools. Before you finish, call remember():\\n\"\n"
        "    \"  - durable=True for each completed, keep-worthy finding (one short paragraph);\\n\"\n"
        "    \"  - durable=False for scratch reasoning or a dead end you do NOT want kept.\\n\"\n"
        "    \"You never choose folders or paths - remember() files each note where it belongs.\"\n"
        ")\n"
        "\n"
        "PRODUCER_TOOLS = {**TOOLBOX, \"remember\": remember}\n"
        "_pmodel = CHAT.bind_tools(list(PRODUCER_TOOLS.values()))\n"
        "_cfg = {\"callbacks\": [HANDLER]} if HANDLER else {}\n"
        "task = (f\"Inspect {ASSET_A} pier 2 for bearing-plate corrosion: check similar past\"\n"
        "        f\" findings first, record a finding if the evidence warrants it, and remember\"\n"
        "        f\" what matters (and explicitly discard your scratch reasoning).\")\n"
        "msgs = [SystemMessage(content=PRODUCER_PROMPT), HumanMessage(content=task)]\n"
        "\n"
        "for _ in range(6):\n"
        "    resp = _pmodel.invoke(msgs, config=_cfg)\n"
        "    msgs.append(resp)\n"
        "    if not getattr(resp, \"tool_calls\", None):\n"
        "        break\n"
        "    for tc in resp.tool_calls:\n"
        "        try:\n"
        "            result = str(PRODUCER_TOOLS[tc[\"name\"]].invoke(tc[\"args\"], _cfg))\n"
        "        except Exception as e:\n"
        "            result = f\"ERROR: {type(e).__name__}: {e}\"\n"
        "        if tc[\"name\"] == \"remember\":\n"
        "            print(f\"  remember(durable={tc['args'].get('durable')}) -> {result}\")\n"
        "        else:\n"
        "            print(f\"  {tc['name']}(...) = {result[:60]}\")\n"
        "        msgs.append(ToolMessage(content=result, tool_call_id=tc[\"id\"]))\n"
        "\n"
        "_ans = resp.content if isinstance(resp.content, str) else \"\".join(\n"
        "    p.get(\"text\", \"\") if isinstance(p, dict) else str(p) for p in resp.content)\n"
        "print(\"\\nagent:\", _ans.strip()[:280])"
    ),
    md(
        "**What the agent filed.** The inbox notes here are exactly what notebook 02's\n"
        "producer job would stage and its triage gate would curate - the two halves, connected."
    ),
    code(
        "with conn.cursor() as cur:\n"
        "    cur.execute(\"SELECT path, status FROM HARNESS_SCRATCH ORDER BY path\")\n"
        "    filed = cur.fetchall()\n"
        "for path, status in filed:\n"
        "    print(f\"  {status}  {path}\")\n"
        "\n"
        "inbox = [p for p, _ in filed if promote.triage_allowed(p)]\n"
        "check(bool(inbox),\n"
        "      f\"the copilot filed a durable note into the inbox: {inbox}\")\n"
        "check(all(promote.triage_allowed(p) for p in inbox),\n"
        "      \"every note the agent marked durable landed where notebook 02 will promote from\")\n"
        "ok(\"producer wired - notebook 02's pipeline consumes exactly these /inbox notes\")"
    ),
]

# --------------------------------------------------------------------------
# Section: anatomy of one run_and_learn (slow motion)
# --------------------------------------------------------------------------
ANATOMY = [
    md(
        "## 7c · Anatomy of one `run_and_learn`, in slow motion\n\n"
        "The arc below calls `run_and_learn` as a black box. Before that, here is **one** call\n"
        "opened up - the same six moving parts, run by hand on a throwaway task, printing what\n"
        "each step decides and **which table each write lands in**. Run the cells in order and\n"
        "watch the database change under you.\n\n"
        "> The `run_and_learn` black box = STEP 3 (act) + STEP 4 (judge) + STEP 5 (capture) +\n"
        "> STEP 6 (learn). STEPs 1-2 happen *inside* STEP 3, but we surface them so the tool /\n"
        "> skill retrieval is visible too. Every function called here is the real one.\n\n"
        "For the model's own reasoning at STEPs 3-4, open the matching Langfuse trace; this\n"
        "teardown is the half Langfuse cannot show you - the SQL writes."
    ),
    code(
        "def _count(sql):\n"
        "    with conn.cursor() as cur:\n"
        "        cur.execute(sql)\n"
        "        return cur.fetchone()[0]\n"
        "\n"
        "# This task deliberately needs a COLD tool (recent findings / asset class), so we\n"
        "# can watch the agent open a capability during STEP 3.\n"
        "ANATOMY_TASK = (f\"Review {ASSET_A}: pull its recent findings and its asset class, then\"\n"
        "                f\" you MUST record a new finding (log it) for a cracked weld at the\"\n"
        "                f\" pier-4 girder seam, severity high. Do not stop until it is recorded.\")\n"
        "print(\"one task, opened up:\\n \", ANATOMY_TASK)"
    ),
    md(
        "**STEP 1 · What the agent starts with.** No similarity search - it begins with the\n"
        "**hot** tools plus `open_capability`, and reads the routing rubric to decide when to\n"
        "reach for more.\n"
        "*Look for:* the small hot set, and the *if you need X → open A* rubric. The cold\n"
        "tools are not bound yet - the agent will disclose a group in STEP 3."
    ),
    code(
        "print(\"hot tools (always bound):\", HOT)\n"
        "print(\"meta-tool             :\", [\"open_capability\"])\n"
        "print(\"\\ncapability rubric the agent reads:\\n\" + CAPABILITY_RUBRIC)"
    ),
    md(
        "**STEP 2 · Retrieve skills.** `build_skill_manifest` does the same distance-gated\n"
        "lookup over `HARNESS_SKILLS`, approved-before-provisional.\n"
        "*Look for:* `none` here - no skill has been harvested yet, so there is nothing to\n"
        "inject. This is the step that will light up *after* the arc harvests one."
    ),
    code(
        "_manifest, _sids = build_skill_manifest(ANATOMY_TASK)\n"
        "print(f\"  skills injected: {_sids or 'none (none harvested yet, or none within distance)'}\")"
    ),
    md(
        "**STEP 3 · ACT - the agent loop.** `run_copilot_task` binds the retrieved tools and\n"
        "iterates model -> tool calls -> results, recording every step as a trajectory.\n"
        "*Look for:* the ordered trajectory, and `CITY_INSPECTION_FINDING` gaining a row when\n"
        "the agent calls `tool_log_finding` - the real domain write."
    ),
    code(
        "_before = _count(\"SELECT COUNT(*) FROM CITY_INSPECTION_FINDING\")\n"
        "# One deliberate run to narrate - but re-run if the agent explored without\n"
        "# actually logging (same 'act, don't just read' bar run_and_learn enforces).\n"
        "for _attempt in range(4):\n"
        "    _run = run_copilot_task(ANATOMY_TASK)\n"
        "    _after = _count(\"SELECT COUNT(*) FROM CITY_INSPECTION_FINDING\")\n"
        "    if _after > _before:\n"
        "        break\n"
        "for _i, _s in enumerate(_run[\"trajectory\"], 1):\n"
        "    print(f\"    {_i}. {_s['tool']}({_s['args']}) -> {str(_s['result'])[:55]}\")\n"
        "print(f\"  -> CITY_INSPECTION_FINDING: {_before} -> {_after} rows \"\n"
        "      f\"({_after - _before} finding written by the agent)\")"
    ),
    md(
        "**STEP 4 · JUDGE - audit against the database, not the prose.** `build_evidence`\n"
        "re-queries every finding the run claims or cites; the judge sees task + trajectory +\n"
        "answer + that evidence.\n"
        "*Look for:* each write marked `EXISTS`/`NOT FOUND`, then `verified=True/False`. This\n"
        "is the gate that later decides whether the run counts as a success."
    ),
    code(
        "print(\"  evidence (re-queried from the DB):\")\n"
        "for _line in build_evidence(_run[\"answer\"]).splitlines():\n"
        "    print(\"    \" + _line)\n"
        "_verdict = judge_workflow(ANATOMY_TASK, _run)\n"
        "print(f\"  -> verified={_verdict.verified}: {_verdict.reason[:110]}\")"
    ),
    md(
        "**STEP 4b · The judge, up close.** The summary above hides two things worth seeing:\n"
        "*exactly what the judge reads*, and its *full* reasoning. The prompt below is the\n"
        "real audit input - task + trajectory + answer + the DB evidence, re-queried live."
    ),
    code(
        "print(\"===== the exact prompt the judge sees =====\\n\")\n"
        "print(JUDGE_PROMPT.format(\n"
        "    task=ANATOMY_TASK,\n"
        "    trajectory=improve.trajectory_to_text(_run['trajectory']),\n"
        "    answer=_run['answer'],\n"
        "    evidence=build_evidence(_run['answer'])))\n"
        "print(\"\\n===== the judge's FULL reasoning =====\\n\" + _verdict.reason)"
    ),
    md(
        "**Does the DB audit actually bite?** Take the *same* run and fabricate one detail - an\n"
        "extra citation to a finding that does not exist - then re-judge. Only that one variable\n"
        "changes. `build_evidence` re-queries the fake id, finds it missing, and the judge flips\n"
        "to `verified=False`. This is the whole difference from `success = bool(final)`: a\n"
        "confident answer that cites a nonexistent record is **caught**, not trusted."
    ),
    code(
        "# same trajectory + answer, with ONE fabricated finding_id spliced into the answer\n"
        "_faked = {\"trajectory\": _run[\"trajectory\"], \"skill_ids\": _run[\"skill_ids\"],\n"
        "          \"answer\": _run[\"answer\"] + \" Corroborated by prior finding deadbeef-000.\"}\n"
        "print(\"evidence now carries the fabricated citation:\")\n"
        "for _l in build_evidence(_faked['answer']).splitlines():\n"
        "    print(\"   \" + _l)\n"
        "_fake_verdict = judge_workflow(ANATOMY_TASK, _faked)\n"
        "print(f\"\\n  honest run   -> verified={_verdict.verified}\")\n"
        "print(f\"  tampered run -> verified={_fake_verdict.verified}: {_fake_verdict.reason[:150]}\")\n"
        "check(not _fake_verdict.verified,\n"
        "      \"the judge rejects a fabricated citation - the DB audit has teeth\")"
    ),
    md(
        "**STEP 5 · CAPTURE - dedup by meaning, then write the workflow.** The intent is\n"
        "embedded, `_nearest_workflow` finds the closest existing one, and `merge_decision`\n"
        "picks merge / ask-the-LLM / new. Here the table is empty, so it is a clean **insert**.\n"
        "*Look for:* `HARNESS_WORKFLOW` gaining a row, and its counters set by the verdict\n"
        "(`verified_successes` vs `failures`)."
    ),
    code(
        "_ivec = array.array('f', embedder.embed([ANATOMY_TASK])[0].tolist())\n"
        "_near = _nearest_workflow(_ivec)\n"
        "print(\"  nearest existing workflow: \"\n"
        "      + ('none (table empty) -> decision will be NEW' if _near is None\n"
        "         else f\"{_near['workflow_id'][:8]} at distance {_near['distance']:.3f}\"))\n"
        "_wf_before = _count(\"SELECT COUNT(*) FROM HARNESS_WORKFLOW\")\n"
        "_awid = capture_workflow(ANATOMY_TASK, _run, _verdict.verified)\n"
        "_wf_after = _count(\"SELECT COUNT(*) FROM HARNESS_WORKFLOW\")\n"
        "with conn.cursor() as cur:\n"
        "    cur.execute(\"\"\"SELECT occurrences, verified_successes, failures, promoted\n"
        "                   FROM HARNESS_WORKFLOW WHERE workflow_id = :w\"\"\", w=_awid)\n"
        "    _o, _vs, _fa, _pr = cur.fetchone()\n"
        "print(f\"  -> HARNESS_WORKFLOW: {_wf_before} -> {_wf_after} rows | this workflow \"\n"
        "      f\"{_awid[:8]}: occ={_o} verified={_vs} fail={_fa} promoted={_pr}\")"
    ),
    md(
        "**STEP 5b · Dedup, up close - the three bands.** That was a clean insert (empty\n"
        "table). The interesting part is what CAPTURE does when a neighbour already exists. With\n"
        "the workflow we just captured as the only neighbour, here is how three new intents get\n"
        "classified by cosine distance - `merge_decision`'s three bands, with the real numbers.\n"
        "This is the mechanism that makes `occurrences` climb instead of splitting into\n"
        "near-duplicates. Read-only - nothing is written."
    ),
    code(
        "_v = embedder.embed([ANATOMY_TASK])[0]\n"
        "print(f\"intent_embedding: dim={len(_v)}, first 5 = {[round(float(x), 3) for x in _v[:5]]}\\n\")\n"
        "\n"
        "_probes = [\n"
        "    (\"near-paraphrase\",\n"
        "     f\"Check {ASSET_A} for a cracked weld at the girder-bearing seam by pier 4 and log it.\"),\n"
        "    (\"same task, different asset\",\n"
        "     \"Inspect Elm Overpass: a cracked weld at the girder-to-bearing seam near pier 4; log it.\"),\n"
        "    (\"off-topic\", \"Plan the office holiday party and book a caterer.\"),\n"
        "]\n"
        "for _label, _probe in _probes:\n"
        "    _pv = array.array('f', embedder.embed([_probe])[0].tolist())\n"
        "    _near = _nearest_workflow(_pv)\n"
        "    _dist = _near[\"distance\"] if _near else 1.0\n"
        "    _decision = improve.merge_decision(_dist)\n"
        "    if _decision == \"ask\":\n"
        "        _same = _same_task_model.invoke(\n"
        "            f\"Task A: {ANATOMY_TASK}\\nTask B: {_probe}\\n\"\n"
        "            \"Same recurring task? same=true/false.\").same\n"
        "        _decision = f\"ask (gray band) -> LLM same={_same} -> {'merge' if _same else 'new'}\"\n"
        "    print(f\"  {_label:28} distance={_dist:.3f}  ->  {_decision}\")\n"
        "print(\"\\n  bands:  merge < 0.15   |   ask 0.15-0.40   |   new > 0.40\")"
    ),
    md(
        "**STEP 6 · LEARN - feed the verdict back to any skills used.** `update_skill_outcomes`\n"
        "bumps the `uses`/`verified` counters on each skill the run consumed, then\n"
        "`lifecycle_transition` may flip its status.\n"
        "*Look for:* nothing to update *yet* - no skill was injected in STEP 2. This step is\n"
        "the one that turns a provisional skill into an approved one, once skills exist."
    ),
    code(
        "if _sids:\n"
        "    update_skill_outcomes(_sids, _verdict.verified)\n"
        "    print(f\"  updated skill outcomes for: {_sids}\")\n"
        "else:\n"
        "    print(\"  no skill was used (none exist yet) -> nothing to update.\")\n"
        "    print(\"  this is the step that promotes provisional -> approved once the arc harvests one.\")\n"
        "\n"
        "# This was a rehearsal: forget its workflow row so the arc below starts from empty.\n"
        "with conn.cursor() as cur:\n"
        "    cur.execute(\"DELETE FROM HARNESS_WORKFLOW WHERE workflow_id = :w\", w=_awid)\n"
        "conn.commit()\n"
        "ok(\"anatomy done - that is one run_and_learn; the rehearsal row is cleaned up\")"
    ),
    md(
        "**So `run_and_learn` = act → judge → capture → learn**, touching three tables:\n"
        "`CITY_INSPECTION_FINDING` (the domain write), `HARNESS_WORKFLOW` (the captured\n"
        "procedure), and `HARNESS_SKILLS` (outcomes, once a skill exists). The arc below now\n"
        "runs this same call five times - watch the counters you just saw move accumulate."
    ),
]

SECTIONS = [INTRO, SETUP, BOOTSTRAP, REGISTRY_DDL, TOOLBOX_SEC, AGENT_LOOP, JUDGE, CAPTURE, SKILLS_SEC, ANATOMY, DEMO, PRODUCER, CLOSING]


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "name": "harness",
        "display_name": "CityOps Harness",
        "language": "python",
    }
    nb["cells"] = [cell for section in SECTIONS for cell in section]
    return nb


if __name__ == "__main__":
    nbf.write(build(), "notebooks/01_self_improving_copilot_complete.ipynb")
    print("wrote notebooks/01_self_improving_copilot_complete.ipynb")
